=== aradzie/keybr.com/packages/keybr-keyboard-generator/cldr-keyboards-43.0/keyboards/dtd/ldmlKeyboard.dtd
<!--
Copyright Â© 1991-2023 Unicode, Inc.
For terms of use, see http://www.unicode.org/copyright.html
SPDX-License-Identifier: Unicode-DFS-2016
CLDR data files are interpreted according to the LDML specification (http://unicode.org/reports/tr35/)
-->
<!-- Important Note:

The CLDR Keyboard Workgroup is currently developing major changes to the
CLDR keyboard specification.
These changes are targeted for CLDR version 41.

Please see CLDR-15034 for the latest information. -->

<!ELEMENT keyboard ( version, generation?, info?, names, settings?, import*, keyMap+, displayMap?, layer*, vkeys*, transforms*, reorders?, backspaces? ) >
<!ATTLIST keyboard locale CDATA #REQUIRED >
    <!--@MATCH:any/TODO-->

<!ELEMENT version EMPTY >
<!ATTLIST version platform CDATA #REQUIRED >
    <!--@MATCH:version-->
    <!--@VALUE-->
<!ATTLIST version number CDATA #REQUIRED >
    <!--@MATCH:regex/\$Revision.*\$-->
    <!--@METADATA-->
<!ATTLIST version cldrVersion CDATA #FIXED "43" >
    <!--@MATCH:version-->
    <!--@METADATA-->

<!ELEMENT generation EMPTY >
    <!--@DEPRECATED-->
<!ATTLIST generation date CDATA #REQUIRED >
    <!--@VALUE-->
    <!--@DEPRECATED-->

<!ELEMENT info EMPTY >
<!ATTLIST info author CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST info normalization CDATA #IMPLIED >
    <!--@MATCH:literal/NFC, NFD, other-->
    <!--@VALUE-->
<!ATTLIST info layout CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST info indicator CDATA #IMPLIED >
    <!--@VALUE-->

<!ELEMENT names ( name+ ) >

<!ELEMENT name EMPTY >
<!ATTLIST name value CDATA #REQUIRED >
    <!--@MATCH:any-->
    <!--@VALUE-->

<!ELEMENT settings EMPTY >
    <!--@ORDERED-->
<!ATTLIST settings fallback (omit) #IMPLIED >
    <!--@VALUE-->
<!ATTLIST settings transformFailure (omit) #IMPLIED >
    <!--@VALUE-->
<!ATTLIST settings transformPartial (hide) #IMPLIED >
    <!--@VALUE-->

<!ELEMENT import EMPTY >
<!ATTLIST import path CDATA #REQUIRED >

<!ELEMENT keyMap ( map | flicks )+ >
<!ATTLIST keyMap modifiers CDATA #IMPLIED >
    <!--@MATCH:any/TODO-->

<!ELEMENT map EMPTY >
<!ATTLIST map iso CDATA #REQUIRED >
    <!--@MATCH:regex/[A-Z][0-9][0-9]-->
<!ATTLIST map to CDATA #REQUIRED >
    <!--@MATCH:any-->
    <!--@VALUE-->
<!ATTLIST map longPress CDATA #IMPLIED >
    <!--@MATCH:any-->
    <!--@VALUE-->
<!ATTLIST map longpress-status (optional) #IMPLIED >
<!ATTLIST map transform (no) #IMPLIED >
    <!--@VALUE-->
<!ATTLIST map multitap CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST map hint CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST map optional NMTOKEN #IMPLIED >

<!ELEMENT flicks ( flick+ ) >
<!ATTLIST flicks iso CDATA #REQUIRED >
    <!--@MATCH:regex/[A-Z][0-9][0-9]-->

<!ELEMENT flick EMPTY >
<!ATTLIST flick directions NMTOKENS #REQUIRED >
<!ATTLIST flick to CDATA #REQUIRED >
    <!--@VALUE-->

<!ELEMENT displayMap ( display+ ) >

<!ELEMENT display EMPTY >
<!ATTLIST display to CDATA #REQUIRED >
<!ATTLIST display display CDATA #REQUIRED >
    <!--@VALUE-->

<!ELEMENT layer ( row+, switch*, vkeys* ) >
<!ATTLIST layer modifier CDATA #REQUIRED >

<!ELEMENT row EMPTY >
<!ATTLIST row keys CDATA #REQUIRED >

<!ELEMENT switch EMPTY >
<!ATTLIST switch iso CDATA #REQUIRED >
<!ATTLIST switch layer CDATA #REQUIRED >
    <!--@VALUE-->
<!ATTLIST switch display CDATA #REQUIRED >
    <!--@VALUE-->

<!ELEMENT vkeys ( vkey+ ) >
<!ATTLIST vkeys type CDATA #REQUIRED >
    <!--@MATCH:literal/android, chromeos, osx, und, windows-->

<!ELEMENT vkey EMPTY >
<!ATTLIST vkey iso CDATA #REQUIRED >
    <!--@MATCH:regex/[A-Z][0-9][0-9]-->
<!ATTLIST vkey vkey CDATA #REQUIRED >
    <!--@VALUE-->
<!ATTLIST vkey modifier CDATA #IMPLIED >
    <!--@VALUE-->

<!ELEMENT transforms ( transform+ ) >
<!ATTLIST transforms type CDATA #REQUIRED >
    <!--@MATCH:literal/simple, final-->

<!ELEMENT transform EMPTY >
<!ATTLIST transform before CDATA #IMPLIED >
<!ATTLIST transform from CDATA #REQUIRED >
    <!--@MATCH:any-->
<!ATTLIST transform after CDATA #IMPLIED >
<!ATTLIST transform to CDATA #REQUIRED >
    <!--@MATCH:any-->
    <!--@VALUE-->
<!ATTLIST transform error (fail) #IMPLIED >
    <!--@VALUE-->

<!ELEMENT reorders ( reorder+ ) >

<!ELEMENT reorder EMPTY >
<!ATTLIST reorder before CDATA #IMPLIED >
<!ATTLIST reorder from CDATA #REQUIRED >
<!ATTLIST reorder after CDATA #IMPLIED >
<!ATTLIST reorder order CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST reorder tertiary CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST reorder tertiary_base CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST reorder prebase CDATA #IMPLIED >
    <!--@VALUE-->

<!ELEMENT backspaces ( backspace+ ) >

<!ELEMENT backspace EMPTY >
<!ATTLIST backspace before CDATA #IMPLIED >
<!ATTLIST backspace from CDATA #REQUIRED >
<!ATTLIST backspace after CDATA #IMPLIED >
<!ATTLIST backspace to CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST backspace error (fail) #IMPLIED >
    <!--@VALUE-->

=== aradzie/keybr.com/packages/keybr-generators/cldr-keyboards-43.0/keyboards/windows/lv-t-k0-windows-qwerty.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE keyboard SYSTEM "../dtd/ldmlKeyboard.dtd">
<keyboard locale="lv-t-k0-windows-qwerty">
	<version platform="10" number="$Revision$"/>
	<names>
		<name value="Latvian (QWERTY)"/>
	</names>
	<settings fallback="omit" transformPartial="hide"/>
	<keyMap>
		<map iso="E00" to="`"/>
		<map iso="E01" to="1"/>
		<map iso="E02" to="2"/>
		<map iso="E03" to="3"/>
		<map iso="E04" to="4"/>
		<map iso="E05" to="5"/>
		<map iso="E06" to="6"/>
		<map iso="E07" to="7"/>
		<map iso="E08" to="8"/>
		<map iso="E09" to="9"/>
		<map iso="E10" to="0"/>
		<map iso="E11" to="-"/>
		<map iso="E12" to="="/>
		<map iso="D01" to="q"/>
		<map iso="D02" to="w"/>
		<map iso="D03" to="e"/>
		<map iso="D04" to="r"/>
		<map iso="D05" to="t"/>
		<map iso="D06" to="y"/>
		<map iso="D07" to="u"/>
		<map iso="D08" to="i"/>
		<map iso="D09" to="o"/>
		<map iso="D10" to="p"/>
		<map iso="D11" to="["/>
		<map iso="D12" to="]"/>
		<map iso="C01" to="a"/>
		<map iso="C02" to="s"/>
		<map iso="C03" to="d"/>
		<map iso="C04" to="f"/>
		<map iso="C05" to="g"/>
		<map iso="C06" to="h"/>
		<map iso="C07" to="j"/>
		<map iso="C08" to="k"/>
		<map iso="C09" to="l"/>
		<map iso="C10" to=";"/>
		<map iso="C11" to="&apos;"/>
		<map iso="C12" to="°"/> <!-- (key to right of ') -->
		<map iso="B00" to="\"/> <!-- (key to left of Z) -->
		<map iso="B01" to="z"/>
		<map iso="B02" to="x"/>
		<map iso="B03" to="c"/>
		<map iso="B04" to="v"/>
		<map iso="B05" to="b"/>
		<map iso="B06" to="n"/>
		<map iso="B07" to="m"/>
		<map iso="B08" to=","/>
		<map iso="B09" to="."/>
		<map iso="B10" to="/"/>
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="shift">
		<map iso="E00" to="~"/> <!-- ` -->
		<map iso="E01" to="!"/> <!-- 1 -->
		<map iso="E02" to="@"/> <!-- 2 -->
		<map iso="E03" to="#"/> <!-- 3 -->
		<map iso="E04" to="$"/> <!-- 4 -->
		<map iso="E05" to="%"/> <!-- 5 -->
		<map iso="E06" to="^"/> <!-- 6 -->
		<map iso="E07" to="&amp;"/> <!-- 7 -->
		<map iso="E08" to="*"/> <!-- 8 -->
		<map iso="E09" to="("/> <!-- 9 -->
		<map iso="E10" to=")"/> <!-- 0 -->
		<map iso="E11" to="_"/> <!-- - -->
		<map iso="E12" to="+"/> <!-- = -->
		<map iso="D01" to="Q"/>
		<map iso="D02" to="W"/>
		<map iso="D03" to="E"/>
		<map iso="D04" to="R"/>
		<map iso="D05" to="T"/>
		<map iso="D06" to="Y"/>
		<map iso="D07" to="U"/>
		<map iso="D08" to="I"/>
		<map iso="D09" to="O"/>
		<map iso="D10" to="P"/>
		<map iso="D11" to="{"/> <!-- [ -->
		<map iso="D12" to="}"/> <!-- ] -->
		<map iso="C01" to="A"/>
		<map iso="C02" to="S"/>
		<map iso="C03" to="D"/>
		<map iso="C04" to="F"/>
		<map iso="C05" to="G"/>
		<map iso="C06" to="H"/>
		<map iso="C07" to="J"/>
		<map iso="C08" to="K"/>
		<map iso="C09" to="L"/>
		<map iso="C10" to=":"/> <!-- ; -->
		<map iso="C11" to="\u{22}"/> <!-- '  to= "  -->
		<map iso="C12" to="|"/> <!-- (key to right of ')  base=° -->
		<map iso="B00" to="|"/> <!-- (key to left of Z)  base=\ -->
		<map iso="B01" to="Z"/>
		<map iso="B02" to="X"/>
		<map iso="B03" to="C"/>
		<map iso="B04" to="V"/>
		<map iso="B05" to="B"/>
		<map iso="B06" to="N"/>
		<map iso="B07" to="M"/>
		<map iso="B08" to="&lt;"/> <!-- , -->
		<map iso="B09" to="&gt;"/> <!-- . -->
		<map iso="B10" to="?"/> <!-- / -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="caps">
		<map iso="E00" to="`"/>
		<map iso="E01" to="1"/>
		<map iso="E02" to="2"/>
		<map iso="E03" to="3"/>
		<map iso="E04" to="4"/>
		<map iso="E05" to="5"/>
		<map iso="E06" to="6"/>
		<map iso="E07" to="7"/>
		<map iso="E08" to="8"/>
		<map iso="E09" to="9"/>
		<map iso="E10" to="0"/>
		<map iso="E11" to="-"/>
		<map iso="E12" to="="/>
		<map iso="D01" to="Q"/>
		<map iso="D02" to="W"/>
		<map iso="D03" to="E"/>
		<map iso="D04" to="R"/>
		<map iso="D05" to="T"/>
		<map iso="D06" to="Y"/>
		<map iso="D07" to="U"/>
		<map iso="D08" to="I"/>
		<map iso="D09" to="O"/>
		<map iso="D10" to="P"/>
		<map iso="D11" to="["/>
		<map iso="D12" to="]"/>
		<map iso="C01" to="A"/>
		<map iso="C02" to="S"/>
		<map iso="C03" to="D"/>
		<map iso="C04" to="F"/>
		<map iso="C05" to="G"/>
		<map iso="C06" to="H"/>
		<map iso="C07" to="J"/>
		<map iso="C08" to="K"/>
		<map iso="C09" to="L"/>
		<map iso="C10" to=";"/>
		<map iso="C11" to="&apos;"/>
		<map iso="C12" to="°"/> <!-- (key to right of ') -->
		<map iso="B00" to="\"/> <!-- (key to left of Z) -->
		<map iso="B01" to="Z"/>
		<map iso="B02" to="X"/>
		<map iso="B03" to="C"/>
		<map iso="B04" to="V"/>
		<map iso="B05" to="B"/>
		<map iso="B06" to="N"/>
		<map iso="B07" to="M"/>
		<map iso="B08" to=","/>
		<map iso="B09" to="."/>
		<map iso="B10" to="/"/>
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="caps+shift">
		<map iso="E00" to="~"/> <!-- ` -->
		<map iso="E01" to="!"/> <!-- 1 -->
		<map iso="E02" to="@"/> <!-- 2 -->
		<map iso="E03" to="#"/> <!-- 3 -->
		<map iso="E04" to="$"/> <!-- 4 -->
		<map iso="E05" to="%"/> <!-- 5 -->
		<map iso="E06" to="^"/> <!-- 6 -->
		<map iso="E07" to="&amp;"/> <!-- 7 -->
		<map iso="E08" to="*"/> <!-- 8 -->
		<map iso="E09" to="("/> <!-- 9 -->
		<map iso="E10" to=")"/> <!-- 0 -->
		<map iso="E11" to="_"/> <!-- - -->
		<map iso="E12" to="+"/> <!-- = -->
		<map iso="D01" to="q"/>
		<map iso="D02" to="w"/>
		<map iso="D03" to="e"/>
		<map iso="D04" to="r"/>
		<map iso="D05" to="t"/>
		<map iso="D06" to="y"/>
		<map iso="D07" to="u"/>
		<map iso="D08" to="i"/>
		<map iso="D09" to="o"/>
		<map iso="D10" to="p"/>
		<map iso="D11" to="{"/> <!-- [ -->
		<map iso="D12" to="}"/> <!-- ] -->
		<map iso="C01" to="a"/>
		<map iso="C02" to="s"/>
		<map iso="C03" to="d"/>
		<map iso="C04" to="f"/>
		<map iso="C05" to="g"/>
		<map iso="C06" to="h"/>
		<map iso="C07" to="j"/>
		<map iso="C08" to="k"/>
		<map iso="C09" to="l"/>
		<map iso="C10" to=":"/> <!-- ; -->
		<map iso="C11" to="\u{22}"/> <!-- '  to= "  -->
		<map iso="C12" to="|"/> <!-- (key to right of ')  base=° -->
		<map iso="B00" to="|"/> <!-- (key to left of Z)  base=\ -->
		<map iso="B01" to="z"/>
		<map iso="B02" to="x"/>
		<map iso="B03" to="c"/>
		<map iso="B04" to="v"/>
		<map iso="B05" to="b"/>
		<map iso="B06" to="n"/>
		<map iso="B07" to="m"/>
		<map iso="B08" to="&lt;"/> <!-- , -->
		<map iso="B09" to="&gt;"/> <!-- . -->
		<map iso="B10" to="?"/> <!-- / -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="altR+caps? ctrl+alt+caps?">
		<map iso="E00" to="\u{AD}"/> <!-- ` -->
		<map iso="E01" to="\u{A0}"/> <!-- 1 -->
		<map iso="E02" to="«"/> <!-- 2 -->
		<map iso="E03" to="»"/> <!-- 3 -->
		<map iso="E04" to="€"/> <!-- 4 -->
		<map iso="E06" to="’"/> <!-- 6 -->
		<map iso="E11" to="–"/> <!-- - -->
		<map iso="D03" to="ē"/> <!-- E -->
		<map iso="D04" to="ŗ"/> <!-- R -->
		<map iso="D07" to="ū"/> <!-- U -->
		<map iso="D08" to="ī"/> <!-- I -->
		<map iso="D09" to="õ"/> <!-- O -->
		<map iso="C01" to="ā"/> <!-- A -->
		<map iso="C02" to="š"/> <!-- S -->
		<map iso="C05" to="ģ"/> <!-- G -->
		<map iso="C08" to="ķ"/> <!-- K -->
		<map iso="C09" to="ļ"/> <!-- L -->
		<map iso="C11" to="´"/> <!-- ' -->
		<map iso="B01" to="ž"/> <!-- Z -->
		<map iso="B03" to="č"/> <!-- C -->
		<map iso="B06" to="ņ"/> <!-- N -->
	</keyMap>
	<keyMap modifiers="altR+shift+caps? ctrl+alt+shift+caps?">
		<map iso="E04" to="§"/> <!-- 4 -->
		<map iso="E05" to="°" transform="no"/> <!-- 5 -->
		<map iso="E07" to="±"/> <!-- 7 -->
		<map iso="E08" to="×"/> <!-- 8 -->
		<map iso="E11" to="—"/> <!-- - -->
		<map iso="D03" to="Ē"/> <!-- E -->
		<map iso="D04" to="Ŗ"/> <!-- R -->
		<map iso="D07" to="Ū"/> <!-- U -->
		<map iso="D08" to="Ī"/> <!-- I -->
		<map iso="D09" to="Õ"/> <!-- O -->
		<map iso="C01" to="Ā"/> <!-- A -->
		<map iso="C02" to="Š"/> <!-- S -->
		<map iso="C05" to="Ģ"/> <!-- G -->
		<map iso="C08" to="Ķ"/> <!-- K -->
		<map iso="C09" to="Ļ"/> <!-- L -->
		<map iso="C11" to="¨"/> <!-- ' -->
		<map iso="B01" to="Ž"/> <!-- Z -->
		<map iso="B03" to="Č"/> <!-- C -->
		<map iso="B06" to="Ņ"/> <!-- N -->
	</keyMap>
	<keyMap modifiers="ctrl+caps?">
		<map iso="D11" to="\u{1B}"/> <!-- [ -->
		<map iso="D12" to="\u{1D}"/> <!-- ] -->
		<map iso="C12" to="\u{1C}"/> <!-- (key to right of ')  base=° -->
		<map iso="B00" to="\u{1C}"/> <!-- (key to left of Z)  base=\ -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<transforms type="simple">
		<transform from="´ " to="´"/>
		<transform from="´c" to="ć"/>
		<transform from="´C" to="Ć"/>
		<transform from="´e" to="é"/>
		<transform from="´E" to="É"/>
		<transform from="´n" to="ń"/>
		<transform from="´N" to="Ń"/>
		<transform from="´o" to="ó"/>
		<transform from="´O" to="Ó"/>
		<transform from="´s" to="ś"/>
		<transform from="´S" to="Ś"/>
		<transform from="´z" to="ź"/>
		<transform from="´Z" to="Ź"/>
		<transform from="¨ " to="¨"/>
		<transform from="¨a" to="ä"/>
		<transform from="¨A" to="Ä"/>
		<transform from="¨o" to="ö"/>
		<transform from="¨O" to="Ö"/>
		<transform from="¨u" to="ü"/>
		<transform from="¨U" to="Ü"/>
		<transform from="° " to="°"/>
		<transform from="°a" to="å"/>
		<transform from="°A" to="Å"/>
		<transform from="°e" to="ė"/>
		<transform from="°E" to="Ė"/>
		<transform from="°g" to="ġ"/>
		<transform from="°z" to="ż"/>
		<transform from="°Z" to="Ż"/>
		<transform from="~ " to="~"/>
		<transform from="~o" to="õ"/>
		<transform from="~O" to="Õ"/>
	</transforms>
</keyboard>

=== aradzie/keybr.com/packages/keybr-generators/cldr-keyboards-43.0/keyboards/und/dz-t-k0-windows.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE keyboard SYSTEM "../dtd/ldmlKeyboard.dtd">
<!-- ིOfficial dz-BT Keyboard Layout -->
<!-- ིSource: Dzongkha Development Commission -->
<keyboard locale='dz-t-k0-windows'>
	<version platform='6.1' number='$Revision$' />
	<names>
		<name value='Dzongkha' />
	</names>
	<settings fallback='omit' />
	<keyMap>
		<map iso="E00" to="༉" />  <!-- ` -->
		<map iso="E01" to="༡" />  <!-- 1 -->
		<map iso="E02" to="༢" />   <!-- 2 -->
		<map iso="E03" to="༣" /> <!-- 3 -->
		<map iso="E04" to="༤" /> <!-- 4 -->
		<map iso="E05" to="༥" /> <!-- 5 -->
		<map iso="E06" to="༦" /> <!-- 6 -->
		<map iso="E07" to="༧" /> <!-- 7 -->
		<map iso="E08" to="༨" /> <!-- 8 -->
		<map iso="E09" to="༩" /> <!-- 9 -->
		<map iso="E10" to="༠" /> <!-- 0 -->
		<map iso="E11" to="༔" /> <!-- - -->
		<map iso="E12" to="།" /> <!-- = -->
		<map iso="D01" to="ཀ" /> <!-- Q -->
		<map iso="D02" to="ཁ" /> <!-- W -->
		<map iso="D03" to="ག" /> <!-- E -->
		<map iso="D04" to="ང" /> <!-- R -->
		<map iso="D05" to="\u{F72}" /> <!-- T -->
		<map iso="D06" to="\u{F72}" /> <!-- Y -->
		<map iso="D07" to="ེ\u{F72}" /> <!-- U -->
		<map iso="D08" to="\u{F72}" /> <!-- I -->
		<map iso="D09" to="ཅ" /> <!-- O -->
		<map iso="D10" to="ཆ" /> <!-- P -->
		<map iso="D11" to="ཇ" /> <!-- [ -->
		<map iso="D12" to="ཉ" />  <!-- ] -->
		<map iso="C01" to="ཏ" />  <!-- A -->
		<map iso="C02" to="ཐ" />  <!-- S -->
		<map iso="C03" to="ད" /> <!-- D -->
		<map iso="C04" to="ན" /> <!-- F -->
		<map iso="C05" to="པ" /> <!-- G -->
		<map iso="C06" to="ཕ" /> <!-- H -->
		<map iso="C07" to="བ" /> <!-- J -->
		<map iso="C08" to="མ" /> <!-- K -->
		<map iso="C09" to="ཙ" /> <!-- L -->
		<map iso="C10" to="ཚ" /> <!-- ; -->
		<map iso="C11" to="ཛ" /> <!-- ' -->
		<map iso="C12" to="ཝ" />  <!-- \ -->
		<map iso="B01" to="ཞ" /> <!-- Z -->
		<map iso="B02" to="ཟ" /> <!-- X -->
		<map iso="B03" to="འ" />  <!-- C -->
		<map iso="B04" to="ཡ" />  <!-- V -->
		<map iso="B05" to="ར" />  <!-- B -->
		<map iso="B06" to="ལ" />  <!-- N -->
		<map iso="B07" to="ཤ" /> <!-- M -->
		<map iso="B08" to="ས" />  <!-- , -->
		<map iso="B09" to="ཧ" />  <!-- . -->
		<map iso="B10" to="ཨ" />  <!-- / -->
		<map iso="A03" to="་" /> <!-- ིtsheg -->
	</keyMap>
	<keyMap modifiers='shift'>
		<map iso="E00" to="༊" /> <!-- ` -->
		<map iso="E01" to="༄" /> <!-- 1 -->
		<map iso="E02" to="༅" /> <!-- 2 -->
		<map iso="E03" to="༆" /> <!-- 3 -->
		<map iso="E05" to="༎" /> <!-- 5 -->
		<map iso="E06" to="༈" /> <!-- 6 -->
		<map iso="E07" to="༸" /> <!-- 7 -->
		<map iso="E08" to="༴" /> <!-- 8 -->
		<map iso="E09" to="༼" /> <!-- 9 -->
		<map iso="E10" to="༽" /> <!-- 0 -->
		<map iso="E11" to="ཿ" /> <!-- - -->
		<map iso="E12" to="༑" /> <!-- = -->
		<map iso="D01" to="\u{F90}" /> <!-- Q -->
		<map iso="D02" to="\u{F91}" /> <!-- W -->
		<map iso="D03" to="\u{F92}" /> <!-- E -->
		<map iso="D04" to="\u{F94}" />  <!-- R -->
		<map iso="D05" to="\u{F80}" /> <!-- T -->
		<map iso="D06" to="\u{F84}" />  <!-- Y -->
		<map iso="D07" to="\u{F7B}" /> <!-- U -->
		<map iso="D08" to="\u{F7D}" /> <!-- I -->
		<map iso="D09" to="\u{F95}" /> <!-- O -->
		<map iso="D10" to="\u{F96}" /> <!-- P -->
		<map iso="D11" to="\u{F97}" /> <!-- [ -->
		<map iso="D12" to="\u{F99}" /> <!-- ] -->
		<map iso="C01" to="\u{F9F}" />  <!-- A -->
		<map iso="C02" to="\u{FA0}" /> <!-- S -->
		<map iso="C03" to="\u{FA1}" />  <!-- D -->
		<map iso="C04" to="\u{FA3}" />  <!-- F -->
		<map iso="C05" to="\u{FA4}" />   <!-- G -->
		<map iso="C06" to="\u{FA5}" />  <!-- H -->
		<map iso="C07" to="\u{FA6}" />  <!-- J -->
		<map iso="C08" to="\u{FA8}" />  <!-- K -->
		<map iso="C09" to="\u{FA9}" />  <!-- L -->
		<map iso="C10" to="\u{FAA}" />  <!-- : -->
		<map iso="C11" to="\u{FAB}" />  <!-- " -->
		<map iso="C12" to="\u{FAD}" />  <!-- | -->
		<map iso="B01" to="\u{FAE}" /> <!-- Z -->
		<map iso="B02" to="\u{FAF}" />   <!-- X -->
		<map iso="B03" to="\u{F71}" />   <!-- C -->
		<map iso="B04" to="\u{FB1}" />    <!-- V -->
		<map iso="B05" to="\u{FB2}" />    <!-- B -->
		<map iso="B06" to="\u{FB3}" />    <!-- N -->
		<map iso="B07" to="\u{FB4}" />   <!-- M -->
		<map iso="B08" to="\u{FB6}" /> <!-- , -->
		<map iso="B09" to="\u{FB7};" /> <!-- . -->
		<map iso="B10" to="\u{FB8}" /> <!-- / -->
		<map iso="A03" to=" " /> <!-- space -->
	</keyMap>
	<keyMap modifiers='altR+caps? ctrl+alt+caps?'>
		<map iso="E00" to="࿑" /> <!-- ` -->
		<map iso="E01" to="1" />
		<map iso="E02" to="2" />
		<map iso="E03" to="3" />
		<map iso="E04" to="4" />
		<map iso="E05" to="5" />
		<map iso="E06" to="6" />
		<map iso="E07" to="7" />
		<map iso="E08" to="8" />
		<map iso="E09" to="9" />
		<map iso="E10" to="0" />
		<map iso="E11" to="-" />
		<map iso="E12" to="=" />
		<map iso="D01" to="éྈ" /> <!-- Q -->
		<map iso="D02" to="ྉ" /> <!-- W -->
		<map iso="D03" to="\u{F8C}" /> <!-- E -->
		<map iso="D04" to="ú\u{F83}" /> <!-- R -->
		<map iso="D05" to="ú༚" /> <!-- T -->
		<map iso="D06" to="༛ú" /> <!-- Y -->
		<map iso="D07" to="ú༜" /> <!-- U -->
		<map iso="D08" to="í༝" /> <!-- I -->
		<map iso="D09" to="ó༞" /> <!-- O -->
		<map iso="D10" to="༟" /> <!-- P -->
		<map iso="D11" to="ྗ(" />  <!-- [ -->
		<map iso="D12" to=")" /> <!-- ] -->
		<map iso="C01" to="ཊ" />     <!-- A -->
		<map iso="C02" to="ྫཋ" /> <!-- S -->
		<map iso="C03" to="ཌ" /> <!-- D -->
		<map iso="C04" to="ཎ" /> <!-- F -->
		<map iso="C07" to="\u{F37}" /> <!-- J -->
		<map iso="C08" to="\u{F7E}" /> <!-- K -->
		<map iso="C09" to="\u{F39}" /> <!-- L -->
		<map iso="C10" to=";" /> <!-- ; -->
		<map iso="C11" to="-" />  <!-- ' -->
		<map iso="C12" to="\" />  <!-- \ -->
		<map iso="B01" to="༓" />  <!-- Z -->
		<map iso="B02" to="྾" /> <!-- X -->
		<map iso="B03" to="༃" /> <!-- C -->
		<map iso="B04" to="༏" /> <!-- V -->
		<map iso="B05" to="ཪ" /> <!-- B --> <!-- FIXED FORM RA -->
		<map iso="B06" to="༒" /> <!-- N -->
		<map iso="B07" to="ཥ" /> <!-- M -->
		<map iso="B08" to="," /> <!-- , -->
		<map iso="B09" to="." /> <!-- . -->
		<map iso="B10" to="/" /> <!-- / -->
		<map iso="A03" to="༌" /> <!-- ིnon-breaking tsheg -->
	</keyMap>
	<keyMap modifiers='altR+shift+caps? ctrl+alt+shift+caps?'>
		<map iso="E00" to="࿐" />
		<map iso="E01" to="\u{FD3}" />  <!-- 1 -->
		<map iso="E02" to="\u{FD4}" /> <!-- 2 -->
		<map iso="E03" to="༺" /> <!-- 3 -->
		<map iso="E04" to="༻" /> <!-- 4 -->
		<map iso="E05" to="༐" /> <!-- 5 -->
		<map iso="E06" to="༁" /> <!-- 6 -->
		<map iso="E07" to="ྊ" /> <!-- 7 -->
		<map iso="E08" to="*" /> <!-- 8 -->
		<map iso="E11" to="\u{FD2}" /> <!-- - -->
		<map iso="E12" to="+" />  <!-- = -->
		<map iso="D01" to="\u{F8D}" /> <!-- Q -->
		<map iso="D02" to="\u{F8E}" /> <!-- 0 -->
		<map iso="D03" to="\u{F8F}" /> <!-- 0 -->
		<map iso="D04" to="\u{FD2}" /> <!-- 0 -->
		<map iso="D05" to="\u{F8B}\u{F99}" /> <!-- 0 -->
		<map iso="D08" to="༗" />  <!-- I -->
		<map iso="D09" to="\u{F18}" /> <!-- O -->
		<map iso="D10" to="\u{F19}" /> <!-- P -->
		<map iso="D11" to="\u{F3F}" /> <!-- [ -->
		<map iso="D12" to="\u{F3E}" /> <!-- ] -->
		<map iso="C01" to="\u{F9A}" /><!-- A -->
		<map iso="C02" to="\u{F9B}" /> <!-- S -->
		<map iso="C03" to="\u{F9C}" /> <!-- D -->
		<map iso="C04" to="\u{F9E}" /> <!-- F -->
		<map iso="C07" to="\u{F35}" /> <!-- J -->
		<map iso="C08" to="\u{F87}" /> <!-- K -->
		<map iso="C09" to="\u{F86}" /> <!-- L -->
		<map iso="C10" to=":" /> <!-- ; -->
		<map iso="C11" to="\u{22}" />  <!-- ' -->
		<map iso="C12" to="\u{FBA}" />  <!-- \ -->
		<map iso="B01" to="༶" /> <!-- Z -->
		<map iso="B02" to="྿" /> <!-- X -->
		<map iso="B03" to="\u{FB0}" /> <!-- C -->
		<map iso="B04" to="\u{FBB}" /> <!-- V -->
		<map iso="B05" to="\u{FBC}" /> <!-- B -->
		<map iso="B07" to="\u{FB5}" /> <!-- M -->
		<map iso="B08" to="\u{FD9}" /> <!-- , -->
		<map iso="B09" to="\u{FDA}" /><!-- . -->
		<map iso="B10" to="?" />  <!-- ? -->
		<map iso="A03" to=" " /> <!-- ིnon-breaking space -->
	</keyMap>
</keyboard>

=== aradzie/keybr.com/packages/keybr-generators/cldr-keyboards-43.0/keyboards/windows/ta-t-k0-windows.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE keyboard SYSTEM "../dtd/ldmlKeyboard.dtd">
<keyboard locale="ta-t-k0-windows">
	<version platform="10" number="$Revision$"/>
	<names>
		<name value="Tamil"/>
	</names>
	<settings fallback="omit"/>
	<keyMap>
		<map iso="E00" to="\u{BCA}"/> <!-- `  to= ொ  -->
		<map iso="E01" to="1"/>
		<map iso="E02" to="2"/>
		<map iso="E03" to="3"/>
		<map iso="E04" to="4"/>
		<map iso="E05" to="5"/>
		<map iso="E06" to="6"/>
		<map iso="E07" to="7"/>
		<map iso="E08" to="8"/>
		<map iso="E09" to="9"/>
		<map iso="E10" to="0"/>
		<map iso="E11" to="-"/>
		<map iso="D01" to="\u{BCC}"/> <!-- Q  to= ௌ  -->
		<map iso="D02" to="\u{BC8}"/> <!-- W  to= ை  -->
		<map iso="D03" to="\u{BBE}"/> <!-- E  to= ா  -->
		<map iso="D04" to="\u{BC0}"/> <!-- R  to= ீ  -->
		<map iso="D05" to="\u{BC2}"/> <!-- T  to= ூ  -->
		<map iso="D06" to="ப"/> <!-- Y -->
		<map iso="D07" to="ஹ"/> <!-- U -->
		<map iso="D08" to="க"/> <!-- I -->
		<map iso="D09" to="த"/> <!-- O -->
		<map iso="D10" to="ஜ"/> <!-- P -->
		<map iso="D11" to="ட"/> <!-- [ -->
		<map iso="D12" to="ஞ"/> <!-- ] -->
		<map iso="C01" to="\u{BCB}"/> <!-- A  to= ோ  -->
		<map iso="C02" to="\u{BC7}"/> <!-- S  to= ே  -->
		<map iso="C03" to="\u{BCD}"/> <!-- D  to= ்  -->
		<map iso="C04" to="\u{BBF}"/> <!-- F  to= ி  -->
		<map iso="C05" to="\u{BC1}"/> <!-- G  to= ு  -->
		<map iso="C06" to="ப"/> <!-- H -->
		<map iso="C07" to="ர"/> <!-- J -->
		<map iso="C08" to="க"/> <!-- K -->
		<map iso="C09" to="த"/> <!-- L -->
		<map iso="C10" to="ச"/> <!-- ; -->
		<map iso="C11" to="ட"/> <!-- ' -->
		<map iso="B01" to="\u{BC6}"/> <!-- Z  to= ெ  -->
		<map iso="B03" to="ம"/> <!-- C -->
		<map iso="B04" to="ந"/> <!-- V -->
		<map iso="B05" to="வ"/> <!-- B -->
		<map iso="B06" to="ல"/> <!-- N -->
		<map iso="B07" to="ஸ"/> <!-- M -->
		<map iso="B08" to=","/>
		<map iso="B09" to="."/>
		<map iso="B10" to="ய"/> <!-- / -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="shift+caps?">
		<map iso="E00" to="ஒ"/> <!-- `  base=ொ -->
		<map iso="E06" to="த\u{BCD}ர"/> <!-- 6  to= த்ர  -->
		<map iso="E07" to="க\u{BCD}ஷ"/> <!-- 7  to= க்ஷ  -->
		<map iso="E08" to="ஷ\u{BCD}ர"/> <!-- 8  to= ஷ்ர  -->
		<map iso="E10" to="௰"/> <!-- 0 -->
		<map iso="E11" to="ஃ"/> <!-- - -->
		<map iso="D01" to="ஔ"/> <!-- Q  base=ௌ -->
		<map iso="D02" to="ஐ"/> <!-- W  base=ை -->
		<map iso="D03" to="ஆ"/> <!-- E  base=ா -->
		<map iso="D04" to="ஈ"/> <!-- R  base=ீ -->
		<map iso="D05" to="ஊ"/> <!-- T  base=ூ -->
		<map iso="D06" to="ப"/> <!-- Y -->
		<map iso="D07" to="ங"/> <!-- U  base=ஹ -->
		<map iso="D08" to="க"/> <!-- I -->
		<map iso="D09" to="த"/> <!-- O -->
		<map iso="D10" to="ச"/> <!-- P  base=ஜ -->
		<map iso="D11" to="ட"/> <!-- [ -->
		<map iso="D12" to="ஞ"/> <!-- ] -->
		<map iso="C01" to="ஓ"/> <!-- A  base=ோ -->
		<map iso="C02" to="ஏ"/> <!-- S  base=ே -->
		<map iso="C03" to="அ"/> <!-- D  base=் -->
		<map iso="C04" to="இ"/> <!-- F  base=ி -->
		<map iso="C05" to="உ"/> <!-- G  base=ு -->
		<map iso="C06" to="ப"/> <!-- H -->
		<map iso="C07" to="ற"/> <!-- J  base=ர -->
		<map iso="C08" to="க"/> <!-- K -->
		<map iso="C09" to="த"/> <!-- L -->
		<map iso="C10" to="ச"/> <!-- ; -->
		<map iso="C11" to="ட"/> <!-- ' -->
		<map iso="B01" to="எ"/> <!-- Z  base=ெ -->
		<map iso="B02" to="ௐ"/> <!-- X -->
		<map iso="B03" to="ண"/> <!-- C  base=ம -->
		<map iso="B04" to="ன"/> <!-- V  base=ந -->
		<map iso="B05" to="ழ"/> <!-- B  base=வ -->
		<map iso="B06" to="ள"/> <!-- N  base=ல -->
		<map iso="B07" to="ஶ"/> <!-- M  base=ஸ -->
		<map iso="B08" to="ஷ"/> <!-- , -->
		<map iso="B09" to="ஸ\u{BCD}ர\u{BC0}"/> <!-- .  to= ஸ்ரீ  -->
		<map iso="B10" to="ய"/> <!-- / -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="altR+caps? ctrl+alt+caps?">
		<map iso="E01" to="௧"/> <!-- 1 -->
		<map iso="E02" to="௨"/> <!-- 2 -->
		<map iso="E03" to="௩"/> <!-- 3 -->
		<map iso="E04" to="௪"/> <!-- 4 -->
		<map iso="E05" to="௫"/> <!-- 5 -->
		<map iso="E06" to="௬"/> <!-- 6 -->
		<map iso="E07" to="௭"/> <!-- 7 -->
		<map iso="E08" to="௮"/> <!-- 8 -->
		<map iso="E09" to="௯"/> <!-- 9 -->
		<map iso="E10" to="௦"/> <!-- 0 -->
		<map iso="E11" to="௱"/> <!-- - -->
		<map iso="E12" to="௲"/> <!-- = -->
		<map iso="D06" to="௷"/> <!-- Y  base=ப -->
		<map iso="C06" to="௶"/> <!-- H  base=ப -->
		<map iso="B01" to="௹"/> <!-- Z  base=ெ -->
		<map iso="B02" to="௺"/> <!-- X -->
		<map iso="B03" to="௴"/> <!-- C  base=ம -->
		<map iso="B04" to="௳"/> <!-- V  base=ந -->
		<map iso="B05" to="௵"/> <!-- B  base=வ -->
		<map iso="B06" to="௸"/> <!-- N  base=ல -->
	</keyMap>
	<keyMap modifiers="ctrl+shift+caps?">
		<map iso="E01" to="\u{200D}"/> <!-- 1 -->
		<map iso="E02" to="\u{200C}"/> <!-- 2 -->
		<map iso="E04" to="₹"/> <!-- 4 -->
	</keyMap>
</keyboard>
