=== aradzie/keybr.com/packages/keybr-keyboard-generator/cldr-keyboards-43.0/keyboards/dtd/ldmlKeyboard.dtd
<!--
Copyright Â© 1991-2023 Unicode, Inc.
For terms of use, see http://www.unicode.org/copyright.html
SPDX-License-Identifier: Unicode-DFS-2016
CLDR data files are interpreted according to the LDML specification (http://unicode.org/reports/tr35/)
-->
<!-- Important Note:

The CLDR Keyboard Workgroup is currently developing major changes to the
CLDR keyboard specification.
These changes are targeted for CLDR version 41.

Please see CLDR-15034 for the latest information. -->

<!ELEMENT keyboard ( version, generation?, info?, names, settings?, import*, keyMap+, displayMap?, layer*, vkeys*, transforms*, reorders?, backspaces? ) >
<!ATTLIST keyboard locale CDATA #REQUIRED >
    <!--@MATCH:any/TODO-->

<!ELEMENT version EMPTY >
<!ATTLIST version platform CDATA #REQUIRED >
    <!--@MATCH:version-->
    <!--@VALUE-->
<!ATTLIST version number CDATA #REQUIRED >
    <!--@MATCH:regex/\$Revision.*\$-->
    <!--@METADATA-->
<!ATTLIST version cldrVersion CDATA #FIXED "43" >
    <!--@MATCH:version-->
    <!--@METADATA-->

<!ELEMENT generation EMPTY >
    <!--@DEPRECATED-->
<!ATTLIST generation date CDATA #REQUIRED >
    <!--@VALUE-->
    <!--@DEPRECATED-->

<!ELEMENT info EMPTY >
<!ATTLIST info author CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST info normalization CDATA #IMPLIED >
    <!--@MATCH:literal/NFC, NFD, other-->
    <!--@VALUE-->
<!ATTLIST info layout CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST info indicator CDATA #IMPLIED >
    <!--@VALUE-->

<!ELEMENT names ( name+ ) >

<!ELEMENT name EMPTY >
<!ATTLIST name value CDATA #REQUIRED >
    <!--@MATCH:any-->
    <!--@VALUE-->

<!ELEMENT settings EMPTY >
    <!--@ORDERED-->
<!ATTLIST settings fallback (omit) #IMPLIED >
    <!--@VALUE-->
<!ATTLIST settings transformFailure (omit) #IMPLIED >
    <!--@VALUE-->
<!ATTLIST settings transformPartial (hide) #IMPLIED >
    <!--@VALUE-->

<!ELEMENT import EMPTY >
<!ATTLIST import path CDATA #REQUIRED >

<!ELEMENT keyMap ( map | flicks )+ >
<!ATTLIST keyMap modifiers CDATA #IMPLIED >
    <!--@MATCH:any/TODO-->

<!ELEMENT map EMPTY >
<!ATTLIST map iso CDATA #REQUIRED >
    <!--@MATCH:regex/[A-Z][0-9][0-9]-->
<!ATTLIST map to CDATA #REQUIRED >
    <!--@MATCH:any-->
    <!--@VALUE-->
<!ATTLIST map longPress CDATA #IMPLIED >
    <!--@MATCH:any-->
    <!--@VALUE-->
<!ATTLIST map longpress-status (optional) #IMPLIED >
<!ATTLIST map transform (no) #IMPLIED >
    <!--@VALUE-->
<!ATTLIST map multitap CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST map hint CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST map optional NMTOKEN #IMPLIED >

<!ELEMENT flicks ( flick+ ) >
<!ATTLIST flicks iso CDATA #REQUIRED >
    <!--@MATCH:regex/[A-Z][0-9][0-9]-->

<!ELEMENT flick EMPTY >
<!ATTLIST flick directions NMTOKENS #REQUIRED >
<!ATTLIST flick to CDATA #REQUIRED >
    <!--@VALUE-->

<!ELEMENT displayMap ( display+ ) >

<!ELEMENT display EMPTY >
<!ATTLIST display to CDATA #REQUIRED >
<!ATTLIST display display CDATA #REQUIRED >
    <!--@VALUE-->

<!ELEMENT layer ( row+, switch*, vkeys* ) >
<!ATTLIST layer modifier CDATA #REQUIRED >

<!ELEMENT row EMPTY >
<!ATTLIST row keys CDATA #REQUIRED >

<!ELEMENT switch EMPTY >
<!ATTLIST switch iso CDATA #REQUIRED >
<!ATTLIST switch layer CDATA #REQUIRED >
    <!--@VALUE-->
<!ATTLIST switch display CDATA #REQUIRED >
    <!--@VALUE-->

<!ELEMENT vkeys ( vkey+ ) >
<!ATTLIST vkeys type CDATA #REQUIRED >
    <!--@MATCH:literal/android, chromeos, osx, und, windows-->

<!ELEMENT vkey EMPTY >
<!ATTLIST vkey iso CDATA #REQUIRED >
    <!--@MATCH:regex/[A-Z][0-9][0-9]-->
<!ATTLIST vkey vkey CDATA #REQUIRED >
    <!--@VALUE-->
<!ATTLIST vkey modifier CDATA #IMPLIED >
    <!--@VALUE-->

<!ELEMENT transforms ( transform+ ) >
<!ATTLIST transforms type CDATA #REQUIRED >
    <!--@MATCH:literal/simple, final-->

<!ELEMENT transform EMPTY >
<!ATTLIST transform before CDATA #IMPLIED >
<!ATTLIST transform from CDATA #REQUIRED >
    <!--@MATCH:any-->
<!ATTLIST transform after CDATA #IMPLIED >
<!ATTLIST transform to CDATA #REQUIRED >
    <!--@MATCH:any-->
    <!--@VALUE-->
<!ATTLIST transform error (fail) #IMPLIED >
    <!--@VALUE-->

<!ELEMENT reorders ( reorder+ ) >

<!ELEMENT reorder EMPTY >
<!ATTLIST reorder before CDATA #IMPLIED >
<!ATTLIST reorder from CDATA #REQUIRED >
<!ATTLIST reorder after CDATA #IMPLIED >
<!ATTLIST reorder order CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST reorder tertiary CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST reorder tertiary_base CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST reorder prebase CDATA #IMPLIED >
    <!--@VALUE-->

<!ELEMENT backspaces ( backspace+ ) >

<!ELEMENT backspace EMPTY >
<!ATTLIST backspace before CDATA #IMPLIED >
<!ATTLIST backspace from CDATA #REQUIRED >
<!ATTLIST backspace after CDATA #IMPLIED >
<!ATTLIST backspace to CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST backspace error (fail) #IMPLIED >
    <!--@VALUE-->

=== aradzie/keybr.com/packages/keybr-generators/cldr-keyboards-43.0/keyboards/windows/km-t-k0-windows-extended.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE keyboard SYSTEM "../dtd/ldmlKeyboard.dtd">
<keyboard locale="km-t-k0-windows-extended">
	<version platform="10" number="$Revision$"/>
	<names>
		<name value="Khmer (NIDA)"/>
	</names>
	<settings fallback="omit"/>
	<keyMap>
		<map iso="E00" to="«"/> <!-- ` -->
		<map iso="E01" to="១"/> <!-- 1 -->
		<map iso="E02" to="២"/> <!-- 2 -->
		<map iso="E03" to="៣"/> <!-- 3 -->
		<map iso="E04" to="៤"/> <!-- 4 -->
		<map iso="E05" to="៥"/> <!-- 5 -->
		<map iso="E06" to="៦"/> <!-- 6 -->
		<map iso="E07" to="៧"/> <!-- 7 -->
		<map iso="E08" to="៨"/> <!-- 8 -->
		<map iso="E09" to="៩"/> <!-- 9 -->
		<map iso="E10" to="០"/> <!-- 0 -->
		<map iso="E11" to="ឥ"/> <!-- - -->
		<map iso="E12" to="ឲ"/> <!-- = -->
		<map iso="D01" to="ឆ"/> <!-- Q -->
		<map iso="D02" to="\u{17B9}"/> <!-- W  to= ឹ  -->
		<map iso="D03" to="\u{17C1}"/> <!-- E  to= េ  -->
		<map iso="D04" to="រ"/> <!-- R -->
		<map iso="D05" to="ត"/> <!-- T -->
		<map iso="D06" to="យ"/> <!-- Y -->
		<map iso="D07" to="\u{17BB}"/> <!-- U  to= ុ  -->
		<map iso="D08" to="\u{17B7}"/> <!-- I  to= ិ  -->
		<map iso="D09" to="\u{17C4}"/> <!-- O  to= ោ  -->
		<map iso="D10" to="ផ"/> <!-- P -->
		<map iso="D11" to="\u{17C0}"/> <!-- [  to= ៀ  -->
		<map iso="D12" to="ឪ"/> <!-- ] -->
		<map iso="C01" to="\u{17B6}"/> <!-- A  to= ា  -->
		<map iso="C02" to="ស"/> <!-- S -->
		<map iso="C03" to="ដ"/> <!-- D -->
		<map iso="C04" to="ថ"/> <!-- F -->
		<map iso="C05" to="ង"/> <!-- G -->
		<map iso="C06" to="ហ"/> <!-- H -->
		<map iso="C07" to="\u{17D2}"/> <!-- J  to= ្  -->
		<map iso="C08" to="ក"/> <!-- K -->
		<map iso="C09" to="ល"/> <!-- L -->
		<map iso="C10" to="\u{17BE}"/> <!-- ;  to= ើ  -->
		<map iso="C11" to="\u{17CB}"/> <!-- '  to= ់  -->
		<map iso="C12" to="ឮ"/> <!-- (key to right of ') -->
		<map iso="B01" to="ឋ"/> <!-- Z -->
		<map iso="B02" to="ខ"/> <!-- X -->
		<map iso="B03" to="ច"/> <!-- C -->
		<map iso="B04" to="វ"/> <!-- V -->
		<map iso="B05" to="ប"/> <!-- B -->
		<map iso="B06" to="ន"/> <!-- N -->
		<map iso="B07" to="ម"/> <!-- M -->
		<map iso="B08" to="\u{17BB}\u{17C6}"/> <!-- ,  to= ុំ  -->
		<map iso="B09" to="។"/> <!-- . -->
		<map iso="B10" to="\u{17CA}"/> <!-- /  to= ៊  -->
		<map iso="A03" to="\u{200B}"/> <!-- space -->
	</keyMap>
	<keyMap modifiers="shift+caps?">
		<map iso="E00" to="»"/> <!-- `  base=« -->
		<map iso="E01" to="!"/> <!-- 1  base=១ -->
		<map iso="E02" to="ៗ"/> <!-- 2  base=២ -->
		<map iso="E03" to="\u{22}"/> <!-- 3  base=៣  to= "  -->
		<map iso="E04" to="៛"/> <!-- 4  base=៤ -->
		<map iso="E05" to="%"/> <!-- 5  base=៥ -->
		<map iso="E06" to="\u{17CD}"/> <!-- 6  base=៦  to= ៍  -->
		<map iso="E07" to="\u{17D0}"/> <!-- 7  base=៧  to= ័  -->
		<map iso="E08" to="\u{17CF}"/> <!-- 8  base=៨  to= ៏  -->
		<map iso="E09" to="("/> <!-- 9  base=៩ -->
		<map iso="E10" to=")"/> <!-- 0  base=០ -->
		<map iso="E11" to="\u{17CC}"/> <!-- -  base=ឥ  to= ៌  -->
		<map iso="E12" to="="/> <!--   base=ឲ -->
		<map iso="D01" to="ឈ"/> <!-- Q  base=ឆ -->
		<map iso="D02" to="\u{17BA}"/> <!-- W  base=ឹ  to= ឺ  -->
		<map iso="D03" to="\u{17C2}"/> <!-- E  base=េ  to= ែ  -->
		<map iso="D04" to="ឬ"/> <!-- R  base=រ -->
		<map iso="D05" to="ទ"/> <!-- T  base=ត -->
		<map iso="D06" to="\u{17BD}"/> <!-- Y  base=យ  to= ួ  -->
		<map iso="D07" to="\u{17BC}"/> <!-- U  base=ុ  to= ូ  -->
		<map iso="D08" to="\u{17B8}"/> <!-- I  base=ិ  to= ី  -->
		<map iso="D09" to="\u{17C5}"/> <!-- O  base=ោ  to= ៅ  -->
		<map iso="D10" to="ភ"/> <!-- P  base=ផ -->
		<map iso="D11" to="\u{17BF}"/> <!-- [  base=ៀ  to= ឿ  -->
		<map iso="D12" to="ឧ"/> <!-- ]  base=ឪ -->
		<map iso="C01" to="\u{17B6}\u{17C6}"/> <!-- A  base=ា  to= ាំ  -->
		<map iso="C02" to="\u{17C3}"/> <!-- S  base=ស  to= ៃ  -->
		<map iso="C03" to="ឌ"/> <!-- D  base=ដ -->
		<map iso="C04" to="ធ"/> <!-- F  base=ថ -->
		<map iso="C05" to="អ"/> <!-- G  base=ង -->
		<map iso="C06" to="\u{17C7}"/> <!-- H  base=ហ  to= ះ  -->
		<map iso="C07" to="ញ"/> <!-- J  base=្ -->
		<map iso="C08" to="គ"/> <!-- K  base=ក -->
		<map iso="C09" to="ឡ"/> <!-- L  base=ល -->
		<map iso="C10" to="\u{17C4}\u{17C7}"/> <!-- ;  base=ើ  to= ោះ  -->
		<map iso="C11" to="\u{17C9}"/> <!-- '  base=់  to= ៉  -->
		<map iso="C12" to="ឭ"/> <!-- (key to right of ')  base=ឮ -->
		<map iso="B01" to="ឍ"/> <!-- Z  base=ឋ -->
		<map iso="B02" to="ឃ"/> <!-- X  base=ខ -->
		<map iso="B03" to="ជ"/> <!-- C  base=ច -->
		<map iso="B04" to="\u{17C1}\u{17C7}"/> <!-- V  base=វ  to= េះ  -->
		<map iso="B05" to="ព"/> <!-- B  base=ប -->
		<map iso="B06" to="ណ"/> <!-- N  base=ន -->
		<map iso="B07" to="\u{17C6}"/> <!-- M  base=ម  to= ំ  -->
		<map iso="B08" to="\u{17BB}\u{17C7}"/> <!-- ,  base=ុំ  to= ុះ  -->
		<map iso="B09" to="៕"/> <!-- .  base=។ -->
		<map iso="B10" to="?"/> <!-- /  base=៊ -->
		<map iso="A03" to=" "/> <!-- space  base=​ -->
	</keyMap>
	<keyMap modifiers="altR+caps? ctrl+alt+caps?">
		<map iso="E00" to="\u{200D}"/> <!-- `  base=« -->
		<map iso="E01" to="\u{200C}"/> <!-- 1  base=១ -->
		<map iso="E02" to="@"/> <!-- 2  base=២ -->
		<map iso="E03" to="\u{17D1}"/> <!-- 3  base=៣  to= ៑  -->
		<map iso="E04" to="$"/> <!-- 4  base=៤ -->
		<map iso="E05" to="€"/> <!-- 5  base=៥ -->
		<map iso="E06" to="៙"/> <!-- 6  base=៦ -->
		<map iso="E07" to="៚"/> <!-- 7  base=៧ -->
		<map iso="E08" to="*"/> <!-- 8  base=៨ -->
		<map iso="E09" to="{"/> <!-- 9  base=៩ -->
		<map iso="E10" to="}"/> <!-- 0  base=០ -->
		<map iso="E11" to="×"/> <!-- -  base=ឥ -->
		<map iso="E12" to="\u{17CE}"/> <!-- =  base=ឲ  to= ៎  -->
		<map iso="D03" to="ឯ"/> <!-- E  base=េ -->
		<map iso="D04" to="ឫ"/> <!-- R  base=រ -->
		<map iso="D08" to="ឦ"/> <!-- I  base=ិ -->
		<map iso="D09" to="ឱ"/> <!-- O  base=ោ -->
		<map iso="D10" to="ឰ"/> <!-- P  base=ផ -->
		<map iso="D11" to="ឩ"/> <!-- [  base=ៀ -->
		<map iso="D12" to="ឳ"/> <!-- ]  base=ឪ -->
		<map iso="C10" to="៖"/> <!-- ;  base=ើ -->
		<map iso="C11" to="\u{17C8}"/> <!-- '  base=់  to= ៈ  -->
		<map iso="C12" to="\"/> <!-- (key to right of ')  base=ឮ -->
		<map iso="B08" to=","/> <!--   base=ុំ -->
		<map iso="B09" to="."/> <!--   base=។ -->
		<map iso="B10" to="/"/> <!--   base=៊ -->
		<map iso="A03" to="\u{A0}"/> <!-- space  base=​ -->
	</keyMap>
</keyboard>

=== aradzie/keybr.com/packages/keybr-keyboard-generator/cldr-keyboards-43.0/keyboards/windows/mn-t-k0-windows.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE keyboard SYSTEM "../dtd/ldmlKeyboard.dtd">
<keyboard locale="mn-t-k0-windows">
	<version platform="10" number="$Revision$"/>
	<names>
		<name value="Mongolian Cyrillic"/>
	</names>
	<settings fallback="omit"/>
	<keyMap>
		<map iso="E00" to="="/> <!-- ` -->
		<map iso="E01" to="№"/> <!-- 1 -->
		<map iso="E02" to="-"/> <!-- 2 -->
		<map iso="E03" to="\u{22}"/> <!-- 3  to= "  -->
		<map iso="E04" to="₮"/> <!-- 4 -->
		<map iso="E05" to=":"/> <!-- 5 -->
		<map iso="E06" to="."/> <!-- 6 -->
		<map iso="E07" to="_"/> <!-- 7 -->
		<map iso="E08" to=","/> <!-- 8 -->
		<map iso="E09" to="%"/> <!-- 9 -->
		<map iso="E10" to="?"/> <!-- 0 -->
		<map iso="E11" to="е"/> <!-- - -->
		<map iso="E12" to="щ"/> <!-- = -->
		<map iso="D01" to="ф"/> <!-- Q -->
		<map iso="D02" to="ц"/> <!-- W -->
		<map iso="D03" to="у"/> <!-- E -->
		<map iso="D04" to="ж"/> <!-- R -->
		<map iso="D05" to="э"/> <!-- T -->
		<map iso="D06" to="н"/> <!-- Y -->
		<map iso="D07" to="г"/> <!-- U -->
		<map iso="D08" to="ш"/> <!-- I -->
		<map iso="D09" to="ү"/> <!-- O -->
		<map iso="D10" to="з"/> <!-- P -->
		<map iso="D11" to="к"/> <!-- [ -->
		<map iso="D12" to="ъ"/> <!-- ] -->
		<map iso="C01" to="й"/> <!-- A -->
		<map iso="C02" to="ы"/> <!-- S -->
		<map iso="C03" to="б"/> <!-- D -->
		<map iso="C04" to="ө"/> <!-- F -->
		<map iso="C05" to="а"/> <!-- G -->
		<map iso="C06" to="х"/> <!-- H -->
		<map iso="C07" to="р"/> <!-- J -->
		<map iso="C08" to="о"/> <!-- K -->
		<map iso="C09" to="л"/> <!-- L -->
		<map iso="C10" to="д"/> <!-- ; -->
		<map iso="C11" to="п"/> <!-- ' -->
		<map iso="C12" to="\"/> <!-- (key to right of ') -->
		<map iso="B00" to="\"/> <!-- (key to left of Z) -->
		<map iso="B01" to="я"/> <!-- Z -->
		<map iso="B02" to="ч"/> <!-- X -->
		<map iso="B03" to="ё"/> <!-- C -->
		<map iso="B04" to="с"/> <!-- V -->
		<map iso="B05" to="м"/> <!-- B -->
		<map iso="B06" to="и"/> <!-- N -->
		<map iso="B07" to="т"/> <!-- M -->
		<map iso="B08" to="ь"/> <!-- , -->
		<map iso="B09" to="в"/> <!-- . -->
		<map iso="B10" to="ю"/> <!-- / -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="shift">
		<map iso="E00" to="+"/> <!-- `  base== -->
		<map iso="E01" to="1"/> <!--   base=№ -->
		<map iso="E02" to="2"/> <!--   base=- -->
		<map iso="E03" to="3"/> <!--   base=" -->
		<map iso="E04" to="4"/> <!--   base=₮ -->
		<map iso="E05" to="5"/> <!--   base=: -->
		<map iso="E06" to="6"/> <!--   base=. -->
		<map iso="E07" to="7"/> <!--   base=_ -->
		<map iso="E08" to="8"/> <!--   base=, -->
		<map iso="E09" to="9"/> <!--   base=% -->
		<map iso="E10" to="0"/> <!--   base=? -->
		<map iso="E11" to="Е"/> <!-- - -->
		<map iso="E12" to="Щ"/> <!-- = -->
		<map iso="D01" to="Ф"/> <!-- Q -->
		<map iso="D02" to="Ц"/> <!-- W -->
		<map iso="D03" to="У"/> <!-- E -->
		<map iso="D04" to="Ж"/> <!-- R -->
		<map iso="D05" to="Э"/> <!-- T -->
		<map iso="D06" to="Н"/> <!-- Y -->
		<map iso="D07" to="Г"/> <!-- U -->
		<map iso="D08" to="Ш"/> <!-- I -->
		<map iso="D09" to="Ү"/> <!-- O -->
		<map iso="D10" to="З"/> <!-- P -->
		<map iso="D11" to="К"/> <!-- [ -->
		<map iso="D12" to="Ъ"/> <!-- ] -->
		<map iso="C01" to="Й"/> <!-- A -->
		<map iso="C02" to="Ы"/> <!-- S -->
		<map iso="C03" to="Б"/> <!-- D -->
		<map iso="C04" to="Ө"/> <!-- F -->
		<map iso="C05" to="А"/> <!-- G -->
		<map iso="C06" to="Х"/> <!-- H -->
		<map iso="C07" to="Р"/> <!-- J -->
		<map iso="C08" to="О"/> <!-- K -->
		<map iso="C09" to="Л"/> <!-- L -->
		<map iso="C10" to="Д"/> <!-- ; -->
		<map iso="C11" to="П"/> <!-- ' -->
		<map iso="C12" to="|"/> <!-- (key to right of ')  base=\ -->
		<map iso="B00" to="|"/> <!-- (key to left of Z)  base=\ -->
		<map iso="B01" to="Я"/> <!-- Z -->
		<map iso="B02" to="Ч"/> <!-- X -->
		<map iso="B03" to="Ё"/> <!-- C -->
		<map iso="B04" to="С"/> <!-- V -->
		<map iso="B05" to="М"/> <!-- B -->
		<map iso="B06" to="И"/> <!-- N -->
		<map iso="B07" to="Т"/> <!-- M -->
		<map iso="B08" to="Ь"/> <!-- , -->
		<map iso="B09" to="В"/> <!-- . -->
		<map iso="B10" to="Ю"/> <!-- / -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="caps">
		<map iso="E00" to="="/> <!-- ` -->
		<map iso="E01" to="№"/> <!-- 1 -->
		<map iso="E02" to="-"/> <!-- 2 -->
		<map iso="E03" to="\u{22}"/> <!-- 3  to= "  -->
		<map iso="E04" to="₮"/> <!-- 4 -->
		<map iso="E05" to=":"/> <!-- 5 -->
		<map iso="E06" to="."/> <!-- 6 -->
		<map iso="E07" to="_"/> <!-- 7 -->
		<map iso="E08" to=","/> <!-- 8 -->
		<map iso="E09" to="%"/> <!-- 9 -->
		<map iso="E10" to="?"/> <!-- 0 -->
		<map iso="E11" to="Е"/> <!-- - -->
		<map iso="E12" to="Щ"/> <!-- = -->
		<map iso="D01" to="Ф"/> <!-- Q -->
		<map iso="D02" to="Ц"/> <!-- W -->
		<map iso="D03" to="У"/> <!-- E -->
		<map iso="D04" to="Ж"/> <!-- R -->
		<map iso="D05" to="Э"/> <!-- T -->
		<map iso="D06" to="Н"/> <!-- Y -->
		<map iso="D07" to="Г"/> <!-- U -->
		<map iso="D08" to="Ш"/> <!-- I -->
		<map iso="D09" to="Ү"/> <!-- O -->
		<map iso="D10" to="З"/> <!-- P -->
		<map iso="D11" to="К"/> <!-- [ -->
		<map iso="D12" to="Ъ"/> <!-- ] -->
		<map iso="C01" to="Й"/> <!-- A -->
		<map iso="C02" to="Ы"/> <!-- S -->
		<map iso="C03" to="Б"/> <!-- D -->
		<map iso="C04" to="Ө"/> <!-- F -->
		<map iso="C05" to="А"/> <!-- G -->
		<map iso="C06" to="Х"/> <!-- H -->
		<map iso="C07" to="Р"/> <!-- J -->
		<map iso="C08" to="О"/> <!-- K -->
		<map iso="C09" to="Л"/> <!-- L -->
		<map iso="C10" to="Д"/> <!-- ; -->
		<map iso="C11" to="П"/> <!-- ' -->
		<map iso="C12" to="\"/> <!-- (key to right of ') -->
		<map iso="B00" to="\"/> <!-- (key to left of Z) -->
		<map iso="B01" to="Я"/> <!-- Z -->
		<map iso="B02" to="Ч"/> <!-- X -->
		<map iso="B03" to="Ё"/> <!-- C -->
		<map iso="B04" to="С"/> <!-- V -->
		<map iso="B05" to="М"/> <!-- B -->
		<map iso="B06" to="И"/> <!-- N -->
		<map iso="B07" to="Т"/> <!-- M -->
		<map iso="B08" to="Ь"/> <!-- , -->
		<map iso="B09" to="В"/> <!-- . -->
		<map iso="B10" to="Ю"/> <!-- / -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="caps+shift">
		<map iso="E00" to="+"/> <!-- `  base== -->
		<map iso="E01" to="1"/> <!--   base=№ -->
		<map iso="E02" to="2"/> <!--   base=- -->
		<map iso="E03" to="3"/> <!--   base=" -->
		<map iso="E04" to="4"/> <!--   base=₮ -->
		<map iso="E05" to="5"/> <!--   base=: -->
		<map iso="E06" to="6"/> <!--   base=. -->
		<map iso="E07" to="7"/> <!--   base=_ -->
		<map iso="E08" to="8"/> <!--   base=, -->
		<map iso="E09" to="9"/> <!--   base=% -->
		<map iso="E10" to="0"/> <!--   base=? -->
		<map iso="E11" to="е"/> <!-- - -->
		<map iso="E12" to="щ"/> <!-- = -->
		<map iso="D01" to="ф"/> <!-- Q -->
		<map iso="D02" to="ц"/> <!-- W -->
		<map iso="D03" to="у"/> <!-- E -->
		<map iso="D04" to="ж"/> <!-- R -->
		<map iso="D05" to="э"/> <!-- T -->
		<map iso="D06" to="н"/> <!-- Y -->
		<map iso="D07" to="г"/> <!-- U -->
		<map iso="D08" to="ш"/> <!-- I -->
		<map iso="D09" to="ү"/> <!-- O -->
		<map iso="D10" to="з"/> <!-- P -->
		<map iso="D11" to="к"/> <!-- [ -->
		<map iso="D12" to="ъ"/> <!-- ] -->
		<map iso="C01" to="й"/> <!-- A -->
		<map iso="C02" to="ы"/> <!-- S -->
		<map iso="C03" to="б"/> <!-- D -->
		<map iso="C04" to="ө"/> <!-- F -->
		<map iso="C05" to="а"/> <!-- G -->
		<map iso="C06" to="х"/> <!-- H -->
		<map iso="C07" to="р"/> <!-- J -->
		<map iso="C08" to="о"/> <!-- K -->
		<map iso="C09" to="л"/> <!-- L -->
		<map iso="C10" to="д"/> <!-- ; -->
		<map iso="C11" to="п"/> <!-- ' -->
		<map iso="C12" to="|"/> <!-- (key to right of ')  base=\ -->
		<map iso="B00" to="|"/> <!-- (key to left of Z)  base=\ -->
		<map iso="B01" to="я"/> <!-- Z -->
		<map iso="B02" to="ч"/> <!-- X -->
		<map iso="B03" to="ё"/> <!-- C -->
		<map iso="B04" to="с"/> <!-- V -->
		<map iso="B05" to="м"/> <!-- B -->
		<map iso="B06" to="и"/> <!-- N -->
		<map iso="B07" to="т"/> <!-- M -->
		<map iso="B08" to="ь"/> <!-- , -->
		<map iso="B09" to="в"/> <!-- . -->
		<map iso="B10" to="ю"/> <!-- / -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="ctrl+caps?">
		<map iso="C12" to="\u{1C}"/> <!-- (key to right of ')  base=\ -->
		<map iso="B00" to="\u{1C}"/> <!-- (key to left of Z)  base=\ -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
</keyboard>

=== aradzie/keybr.com/packages/keybr-keyboard-generator/cldr-keyboards-43.0/keyboards/android/ka-t-k0-android-768dpi.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE keyboard SYSTEM "../dtd/ldmlKeyboard.dtd">
<keyboard locale="ka-t-k0-android-768dpi">
	<version platform="4.4" number="$Revision$"/>
	<names>
		<name value="Georgian (768dpi)"/>
	</names>
	<keyMap>
		<map iso="D01" to="ქ"/> <!-- Q -->
		<map iso="D02" to="წ"/> <!-- W -->
		<map iso="D03" to="ე" longPress="ჱ"/> <!-- E -->
		<map iso="D04" to="რ"/> <!-- R -->
		<map iso="D05" to="ტ"/> <!-- T -->
		<map iso="D06" to="ყ" longPress="ჸ"/> <!-- Y -->
		<map iso="D07" to="უ"/> <!-- U -->
		<map iso="D08" to="ი" longPress="ჲ"/> <!-- I -->
		<map iso="D09" to="ო"/> <!-- O -->
		<map iso="D10" to="პ"/> <!-- P -->
		<map iso="C01" to="ა" longPress="ჺ"/> <!-- A -->
		<map iso="C02" to="ს"/> <!-- S -->
		<map iso="C03" to="დ"/> <!-- D -->
		<map iso="C04" to="ფ" longPress="ჶ"/> <!-- F -->
		<map iso="C05" to="გ" longPress="ჹ"/> <!-- G -->
		<map iso="C06" to="ჰ" longPress="ჵ"/> <!-- H -->
		<map iso="C07" to="ჯ" longPress="ჷ"/> <!-- J -->
		<map iso="C08" to="კ"/> <!-- K -->
		<map iso="C09" to="ლ"/> <!-- L -->
		<map iso="B01" to="ზ"/> <!-- Z -->
		<map iso="B02" to="ხ" longPress="ჴ"/> <!-- X -->
		<map iso="B03" to="ც"/> <!-- C -->
		<map iso="B04" to="ვ" longPress="ჳ"/> <!-- V -->
		<map iso="B05" to="ბ"/> <!-- B -->
		<map iso="B06" to="ნ" longPress="ჼ"/> <!-- N -->
		<map iso="B07" to="მ"/> <!-- M -->
		<map iso="A02" to=","/> <!-- (key to left of space) -->
		<map iso="A03" to=" "/> <!-- space -->
		<map iso="A04" to="." longPress="# ! , ? - : ' @"/> <!-- (key to right of space) -->
	</keyMap>
	<keyMap modifiers="opt">
		<map iso="D01" to="1" longPress="¹ ½ ⅓ ¼ ⅛"/> <!-- Q  base=ქ -->
		<map iso="D02" to="2" longPress="² ⅔"/> <!-- W  base=წ -->
		<map iso="D03" to="3" longPress="³ ¾ ⅜"/> <!-- E  base=ე -->
		<map iso="D04" to="4" longPress="⁴"/> <!-- R  base=რ -->
		<map iso="D05" to="5" longPress="⅝"/> <!-- T  base=ტ -->
		<map iso="D06" to="6"/> <!-- Y  base=ყ -->
		<map iso="D07" to="7" longPress="⅞"/> <!-- U  base=უ -->
		<map iso="D08" to="8"/> <!-- I  base=ი -->
		<map iso="D09" to="9"/> <!-- O  base=ო -->
		<map iso="D10" to="0" longPress="ⁿ ∅"/> <!-- P  base=პ -->
		<map iso="C01" to="@"/> <!-- A  base=ა -->
		<map iso="C02" to="#"/> <!-- S  base=ს -->
		<map iso="C03" to="$" longPress="¢ £ € ¥ ₱"/> <!-- D  base=დ -->
		<map iso="C04" to="%" longPress="‰"/> <!-- F  base=ფ -->
		<map iso="C05" to="&amp;"/> <!-- G  base=გ -->
		<map iso="C06" to="-" longPress="_ – — ·"/> <!-- H  base=ჰ -->
		<map iso="C07" to="+" longPress="±"/> <!-- J  base=ჯ -->
		<map iso="C08" to="(" longPress="&lt; { ["/> <!-- K  base=კ -->
		<map iso="C09" to=")" longPress="&gt; } ]"/> <!-- L  base=ლ -->
		<map iso="B01" to="*" longPress="† ‡ ★"/> <!-- Z  base=ზ -->
		<map iso="B02" to="\u{22}" longPress="“ ” « »"/> <!-- X  base=ხ  to= "  -->
		<map iso="B03" to="&apos;" longPress="‘ ’ ‹ ›"/> <!-- C  base=ც -->
		<map iso="B04" to=":"/> <!-- V  base=ვ -->
		<map iso="B05" to=";"/> <!-- B  base=ბ -->
		<map iso="B06" to="!" longPress="¡"/> <!-- N  base=ნ -->
		<map iso="B07" to="?" longPress="¿"/> <!-- M  base=მ -->
		<map iso="A00" to="_"/> <!-- (3 keys to left of space) -->
		<map iso="A01" to="/"/> <!-- (2 keys to left of space) -->
		<map iso="A02" to=" "/> <!-- (key to left of space)  base=, -->
		<map iso="A03" to=","/> <!-- space -->
		<map iso="A04" to="."/> <!-- (key to right of space) -->
	</keyMap>
	<keyMap modifiers="opt+shift">
		<map iso="D01" to="~"/> <!-- Q  base=ქ -->
		<map iso="D02" to="`"/> <!-- W  base=წ -->
		<map iso="D03" to="|"/> <!-- E  base=ე -->
		<map iso="D04" to="•" longPress="♪ ♥ ♠ ♦ ♣"/> <!-- R  base=რ -->
		<map iso="D05" to="√"/> <!-- T  base=ტ -->
		<map iso="D06" to="Π" longPress="π"/> <!-- Y  base=ყ -->
		<map iso="D07" to="÷"/> <!-- U  base=უ -->
		<map iso="D08" to="×"/> <!-- I  base=ი -->
		<map iso="D09" to="¶" longPress="§"/> <!-- O  base=ო -->
		<map iso="D10" to="∆"/> <!-- P  base=პ -->
		<map iso="C01" to="£"/> <!-- A  base=ა -->
		<map iso="C02" to="¢"/> <!-- S  base=ს -->
		<map iso="C03" to="€"/> <!-- D  base=დ -->
		<map iso="C04" to="¥"/> <!-- F  base=ფ -->
		<map iso="C05" to="^" longPress="↑ ↓ ← →"/> <!-- G  base=გ -->
		<map iso="C06" to="°" longPress="′ ″"/> <!-- H  base=ჰ -->
		<map iso="C07" to="=" longPress="≠ ≈ ∞"/> <!-- J  base=ჯ -->
		<map iso="C08" to="{"/> <!-- K  base=კ -->
		<map iso="C09" to="}"/> <!-- L  base=ლ -->
		<map iso="B01" to="\"/> <!-- Z  base=ზ -->
		<map iso="B02" to="©"/> <!-- X  base=ხ -->
		<map iso="B03" to="®"/> <!-- C  base=ც -->
		<map iso="B04" to="™"/> <!-- V  base=ვ -->
		<map iso="B05" to="℅"/> <!-- B  base=ბ -->
		<map iso="B06" to="["/> <!-- N  base=ნ -->
		<map iso="B07" to="]"/> <!-- M  base=მ -->
		<map iso="A00" to="&lt;" longPress="‹ ≤ «"/> <!-- (3 keys to left of space) -->
		<map iso="A01" to="&gt;" longPress="› ≥ »"/> <!-- (2 keys to left of space) -->
		<map iso="A02" to=" "/> <!-- (key to left of space)  base=, -->
		<map iso="A03" to=","/> <!-- space -->
		<map iso="A04" to="."/> <!-- (key to right of space) -->
	</keyMap>
</keyboard>
