=== aradzie/keybr.com/packages/keybr-keyboard-generator/cldr-keyboards-43.0/keyboards/dtd/ldmlKeyboard.dtd
<!--
Copyright Â© 1991-2023 Unicode, Inc.
For terms of use, see http://www.unicode.org/copyright.html
SPDX-License-Identifier: Unicode-DFS-2016
CLDR data files are interpreted according to the LDML specification (http://unicode.org/reports/tr35/)
-->
<!-- Important Note:

The CLDR Keyboard Workgroup is currently developing major changes to the
CLDR keyboard specification.
These changes are targeted for CLDR version 41.

Please see CLDR-15034 for the latest information. -->

<!ELEMENT keyboard ( version, generation?, info?, names, settings?, import*, keyMap+, displayMap?, layer*, vkeys*, transforms*, reorders?, backspaces? ) >
<!ATTLIST keyboard locale CDATA #REQUIRED >
    <!--@MATCH:any/TODO-->

<!ELEMENT version EMPTY >
<!ATTLIST version platform CDATA #REQUIRED >
    <!--@MATCH:version-->
    <!--@VALUE-->
<!ATTLIST version number CDATA #REQUIRED >
    <!--@MATCH:regex/\$Revision.*\$-->
    <!--@METADATA-->
<!ATTLIST version cldrVersion CDATA #FIXED "43" >
    <!--@MATCH:version-->
    <!--@METADATA-->

<!ELEMENT generation EMPTY >
    <!--@DEPRECATED-->
<!ATTLIST generation date CDATA #REQUIRED >
    <!--@VALUE-->
    <!--@DEPRECATED-->

<!ELEMENT info EMPTY >
<!ATTLIST info author CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST info normalization CDATA #IMPLIED >
    <!--@MATCH:literal/NFC, NFD, other-->
    <!--@VALUE-->
<!ATTLIST info layout CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST info indicator CDATA #IMPLIED >
    <!--@VALUE-->

<!ELEMENT names ( name+ ) >

<!ELEMENT name EMPTY >
<!ATTLIST name value CDATA #REQUIRED >
    <!--@MATCH:any-->
    <!--@VALUE-->

<!ELEMENT settings EMPTY >
    <!--@ORDERED-->
<!ATTLIST settings fallback (omit) #IMPLIED >
    <!--@VALUE-->
<!ATTLIST settings transformFailure (omit) #IMPLIED >
    <!--@VALUE-->
<!ATTLIST settings transformPartial (hide) #IMPLIED >
    <!--@VALUE-->

<!ELEMENT import EMPTY >
<!ATTLIST import path CDATA #REQUIRED >

<!ELEMENT keyMap ( map | flicks )+ >
<!ATTLIST keyMap modifiers CDATA #IMPLIED >
    <!--@MATCH:any/TODO-->

<!ELEMENT map EMPTY >
<!ATTLIST map iso CDATA #REQUIRED >
    <!--@MATCH:regex/[A-Z][0-9][0-9]-->
<!ATTLIST map to CDATA #REQUIRED >
    <!--@MATCH:any-->
    <!--@VALUE-->
<!ATTLIST map longPress CDATA #IMPLIED >
    <!--@MATCH:any-->
    <!--@VALUE-->
<!ATTLIST map longpress-status (optional) #IMPLIED >
<!ATTLIST map transform (no) #IMPLIED >
    <!--@VALUE-->
<!ATTLIST map multitap CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST map hint CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST map optional NMTOKEN #IMPLIED >

<!ELEMENT flicks ( flick+ ) >
<!ATTLIST flicks iso CDATA #REQUIRED >
    <!--@MATCH:regex/[A-Z][0-9][0-9]-->

<!ELEMENT flick EMPTY >
<!ATTLIST flick directions NMTOKENS #REQUIRED >
<!ATTLIST flick to CDATA #REQUIRED >
    <!--@VALUE-->

<!ELEMENT displayMap ( display+ ) >

<!ELEMENT display EMPTY >
<!ATTLIST display to CDATA #REQUIRED >
<!ATTLIST display display CDATA #REQUIRED >
    <!--@VALUE-->

<!ELEMENT layer ( row+, switch*, vkeys* ) >
<!ATTLIST layer modifier CDATA #REQUIRED >

<!ELEMENT row EMPTY >
<!ATTLIST row keys CDATA #REQUIRED >

<!ELEMENT switch EMPTY >
<!ATTLIST switch iso CDATA #REQUIRED >
<!ATTLIST switch layer CDATA #REQUIRED >
    <!--@VALUE-->
<!ATTLIST switch display CDATA #REQUIRED >
    <!--@VALUE-->

<!ELEMENT vkeys ( vkey+ ) >
<!ATTLIST vkeys type CDATA #REQUIRED >
    <!--@MATCH:literal/android, chromeos, osx, und, windows-->

<!ELEMENT vkey EMPTY >
<!ATTLIST vkey iso CDATA #REQUIRED >
    <!--@MATCH:regex/[A-Z][0-9][0-9]-->
<!ATTLIST vkey vkey CDATA #REQUIRED >
    <!--@VALUE-->
<!ATTLIST vkey modifier CDATA #IMPLIED >
    <!--@VALUE-->

<!ELEMENT transforms ( transform+ ) >
<!ATTLIST transforms type CDATA #REQUIRED >
    <!--@MATCH:literal/simple, final-->

<!ELEMENT transform EMPTY >
<!ATTLIST transform before CDATA #IMPLIED >
<!ATTLIST transform from CDATA #REQUIRED >
    <!--@MATCH:any-->
<!ATTLIST transform after CDATA #IMPLIED >
<!ATTLIST transform to CDATA #REQUIRED >
    <!--@MATCH:any-->
    <!--@VALUE-->
<!ATTLIST transform error (fail) #IMPLIED >
    <!--@VALUE-->

<!ELEMENT reorders ( reorder+ ) >

<!ELEMENT reorder EMPTY >
<!ATTLIST reorder before CDATA #IMPLIED >
<!ATTLIST reorder from CDATA #REQUIRED >
<!ATTLIST reorder after CDATA #IMPLIED >
<!ATTLIST reorder order CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST reorder tertiary CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST reorder tertiary_base CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST reorder prebase CDATA #IMPLIED >
    <!--@VALUE-->

<!ELEMENT backspaces ( backspace+ ) >

<!ELEMENT backspace EMPTY >
<!ATTLIST backspace before CDATA #IMPLIED >
<!ATTLIST backspace from CDATA #REQUIRED >
<!ATTLIST backspace after CDATA #IMPLIED >
<!ATTLIST backspace to CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST backspace error (fail) #IMPLIED >
    <!--@VALUE-->

=== aradzie/keybr.com/packages/keybr-keyboard-generator/cldr-keyboards-43.0/keyboards/windows/ga-t-k0-windows.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE keyboard SYSTEM "../dtd/ldmlKeyboard.dtd">
<keyboard locale="ga-t-k0-windows">
	<version platform="10" number="$Revision$"/>
	<names>
		<name value="Irish"/>
	</names>
	<settings fallback="omit" transformPartial="hide"/>
	<keyMap>
		<map iso="E00" to="`"/>
		<map iso="E01" to="1"/>
		<map iso="E02" to="2"/>
		<map iso="E03" to="3"/>
		<map iso="E04" to="4"/>
		<map iso="E05" to="5"/>
		<map iso="E06" to="6"/>
		<map iso="E07" to="7"/>
		<map iso="E08" to="8"/>
		<map iso="E09" to="9"/>
		<map iso="E10" to="0"/>
		<map iso="E11" to="-"/>
		<map iso="E12" to="="/>
		<map iso="D01" to="q"/>
		<map iso="D02" to="w"/>
		<map iso="D03" to="e"/>
		<map iso="D04" to="r"/>
		<map iso="D05" to="t"/>
		<map iso="D06" to="y"/>
		<map iso="D07" to="u"/>
		<map iso="D08" to="i"/>
		<map iso="D09" to="o"/>
		<map iso="D10" to="p"/>
		<map iso="D11" to="["/>
		<map iso="D12" to="]"/>
		<map iso="C01" to="a"/>
		<map iso="C02" to="s"/>
		<map iso="C03" to="d"/>
		<map iso="C04" to="f"/>
		<map iso="C05" to="g"/>
		<map iso="C06" to="h"/>
		<map iso="C07" to="j"/>
		<map iso="C08" to="k"/>
		<map iso="C09" to="l"/>
		<map iso="C10" to=";"/>
		<map iso="C11" to="&apos;"/>
		<map iso="C12" to="#"/> <!-- (key to right of ') -->
		<map iso="B00" to="\"/> <!-- (key to left of Z) -->
		<map iso="B01" to="z"/>
		<map iso="B02" to="x"/>
		<map iso="B03" to="c"/>
		<map iso="B04" to="v"/>
		<map iso="B05" to="b"/>
		<map iso="B06" to="n"/>
		<map iso="B07" to="m"/>
		<map iso="B08" to=","/>
		<map iso="B09" to="."/>
		<map iso="B10" to="/"/>
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="shift">
		<map iso="E00" to="¬"/> <!-- ` -->
		<map iso="E01" to="!"/> <!-- 1 -->
		<map iso="E02" to="\u{22}"/> <!-- 2  to= "  -->
		<map iso="E03" to="£"/> <!-- 3 -->
		<map iso="E04" to="$"/> <!-- 4 -->
		<map iso="E05" to="%"/> <!-- 5 -->
		<map iso="E06" to="^"/> <!-- 6 -->
		<map iso="E07" to="&amp;"/> <!-- 7 -->
		<map iso="E08" to="*"/> <!-- 8 -->
		<map iso="E09" to="("/> <!-- 9 -->
		<map iso="E10" to=")"/> <!-- 0 -->
		<map iso="E11" to="_"/> <!-- - -->
		<map iso="E12" to="+"/> <!-- = -->
		<map iso="D01" to="Q"/>
		<map iso="D02" to="W"/>
		<map iso="D03" to="E"/>
		<map iso="D04" to="R"/>
		<map iso="D05" to="T"/>
		<map iso="D06" to="Y"/>
		<map iso="D07" to="U"/>
		<map iso="D08" to="I"/>
		<map iso="D09" to="O"/>
		<map iso="D10" to="P"/>
		<map iso="D11" to="{"/> <!-- [ -->
		<map iso="D12" to="}"/> <!-- ] -->
		<map iso="C01" to="A"/>
		<map iso="C02" to="S"/>
		<map iso="C03" to="D"/>
		<map iso="C04" to="F"/>
		<map iso="C05" to="G"/>
		<map iso="C06" to="H"/>
		<map iso="C07" to="J"/>
		<map iso="C08" to="K"/>
		<map iso="C09" to="L"/>
		<map iso="C10" to=":"/> <!-- ; -->
		<map iso="C11" to="@"/> <!-- ' -->
		<map iso="C12" to="~"/> <!-- (key to right of ')  base=# -->
		<map iso="B00" to="|"/> <!-- (key to left of Z)  base=\ -->
		<map iso="B01" to="Z"/>
		<map iso="B02" to="X"/>
		<map iso="B03" to="C"/>
		<map iso="B04" to="V"/>
		<map iso="B05" to="B"/>
		<map iso="B06" to="N"/>
		<map iso="B07" to="M"/>
		<map iso="B08" to="&lt;"/> <!-- , -->
		<map iso="B09" to="&gt;"/> <!-- . -->
		<map iso="B10" to="?"/> <!-- / -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="caps">
		<map iso="E00" to="`"/>
		<map iso="E01" to="1"/>
		<map iso="E02" to="2"/>
		<map iso="E03" to="3"/>
		<map iso="E04" to="4"/>
		<map iso="E05" to="5"/>
		<map iso="E06" to="6"/>
		<map iso="E07" to="7"/>
		<map iso="E08" to="8"/>
		<map iso="E09" to="9"/>
		<map iso="E10" to="0"/>
		<map iso="E11" to="-"/>
		<map iso="E12" to="="/>
		<map iso="D01" to="Q"/>
		<map iso="D02" to="W"/>
		<map iso="D03" to="E"/>
		<map iso="D04" to="R"/>
		<map iso="D05" to="T"/>
		<map iso="D06" to="Y"/>
		<map iso="D07" to="U"/>
		<map iso="D08" to="I"/>
		<map iso="D09" to="O"/>
		<map iso="D10" to="P"/>
		<map iso="D11" to="["/>
		<map iso="D12" to="]"/>
		<map iso="C01" to="A"/>
		<map iso="C02" to="S"/>
		<map iso="C03" to="D"/>
		<map iso="C04" to="F"/>
		<map iso="C05" to="G"/>
		<map iso="C06" to="H"/>
		<map iso="C07" to="J"/>
		<map iso="C08" to="K"/>
		<map iso="C09" to="L"/>
		<map iso="C10" to=";"/>
		<map iso="C11" to="&apos;"/>
		<map iso="C12" to="#"/> <!-- (key to right of ') -->
		<map iso="B00" to="\"/> <!-- (key to left of Z) -->
		<map iso="B01" to="Z"/>
		<map iso="B02" to="X"/>
		<map iso="B03" to="C"/>
		<map iso="B04" to="V"/>
		<map iso="B05" to="B"/>
		<map iso="B06" to="N"/>
		<map iso="B07" to="M"/>
		<map iso="B08" to=","/>
		<map iso="B09" to="."/>
		<map iso="B10" to="/"/>
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="caps+shift">
		<map iso="E00" to="¬"/> <!-- ` -->
		<map iso="E01" to="!"/> <!-- 1 -->
		<map iso="E02" to="\u{22}"/> <!-- 2  to= "  -->
		<map iso="E03" to="£"/> <!-- 3 -->
		<map iso="E04" to="$"/> <!-- 4 -->
		<map iso="E05" to="%"/> <!-- 5 -->
		<map iso="E06" to="^"/> <!-- 6 -->
		<map iso="E07" to="&amp;"/> <!-- 7 -->
		<map iso="E08" to="*"/> <!-- 8 -->
		<map iso="E09" to="("/> <!-- 9 -->
		<map iso="E10" to=")"/> <!-- 0 -->
		<map iso="E11" to="_"/> <!-- - -->
		<map iso="E12" to="+"/> <!-- = -->
		<map iso="D01" to="q"/>
		<map iso="D02" to="w"/>
		<map iso="D03" to="e"/>
		<map iso="D04" to="r"/>
		<map iso="D05" to="t"/>
		<map iso="D06" to="y"/>
		<map iso="D07" to="u"/>
		<map iso="D08" to="i"/>
		<map iso="D09" to="o"/>
		<map iso="D10" to="p"/>
		<map iso="D11" to="{"/> <!-- [ -->
		<map iso="D12" to="}"/> <!-- ] -->
		<map iso="C01" to="a"/>
		<map iso="C02" to="s"/>
		<map iso="C03" to="d"/>
		<map iso="C04" to="f"/>
		<map iso="C05" to="g"/>
		<map iso="C06" to="h"/>
		<map iso="C07" to="j"/>
		<map iso="C08" to="k"/>
		<map iso="C09" to="l"/>
		<map iso="C10" to=":"/> <!-- ; -->
		<map iso="C11" to="@"/> <!-- ' -->
		<map iso="C12" to="~"/> <!-- (key to right of ')  base=# -->
		<map iso="B00" to="|"/> <!-- (key to left of Z)  base=\ -->
		<map iso="B01" to="z"/>
		<map iso="B02" to="x"/>
		<map iso="B03" to="c"/>
		<map iso="B04" to="v"/>
		<map iso="B05" to="b"/>
		<map iso="B06" to="n"/>
		<map iso="B07" to="m"/>
		<map iso="B08" to="&lt;"/> <!-- , -->
		<map iso="B09" to="&gt;"/> <!-- . -->
		<map iso="B10" to="?"/> <!-- / -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="altR+caps? ctrl+alt+caps?">
		<map iso="E00" to="¦"/> <!-- ` -->
		<map iso="E04" to="€"/> <!-- 4 -->
		<map iso="D03" to="é"/> <!-- E -->
		<map iso="D07" to="ú"/> <!-- U -->
		<map iso="D08" to="í"/> <!-- I -->
		<map iso="D09" to="ó"/> <!-- O -->
		<map iso="C01" to="á"/> <!-- A -->
		<map iso="C11" to="´"/> <!-- ' -->
	</keyMap>
	<keyMap modifiers="altR+shift+caps? ctrl+alt+shift+caps?">
		<map iso="E00" to="¦"/> <!-- ` -->
		<map iso="D03" to="É"/> <!-- E -->
		<map iso="D07" to="Ú"/> <!-- U -->
		<map iso="D08" to="Í"/> <!-- I -->
		<map iso="D09" to="Ó"/> <!-- O -->
		<map iso="C01" to="Á"/> <!-- A -->
		<map iso="C11" to="`" transform="no"/> <!-- ' -->
	</keyMap>
	<keyMap modifiers="ctrl+caps?">
		<map iso="D11" to="\u{1B}"/> <!-- [ -->
		<map iso="D12" to="\u{1D}"/> <!-- ] -->
		<map iso="C12" to="\u{1C}"/> <!-- (key to right of ')  base=# -->
		<map iso="B00" to="\u{1C}"/> <!-- (key to left of Z)  base=\ -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<transforms type="simple">
		<transform from="` " to="`"/>
		<transform from="`a" to="à"/>
		<transform from="`A" to="À"/>
		<transform from="`e" to="è"/>
		<transform from="`E" to="È"/>
		<transform from="`i" to="ì"/>
		<transform from="`I" to="Ì"/>
		<transform from="`o" to="ò"/>
		<transform from="`O" to="Ò"/>
		<transform from="`u" to="ù"/>
		<transform from="`U" to="Ù"/>
		<transform from="´ " to="´"/>
		<transform from="´a" to="á"/>
		<transform from="´A" to="Á"/>
		<transform from="´e" to="é"/>
		<transform from="´E" to="É"/>
		<transform from="´i" to="í"/>
		<transform from="´I" to="Í"/>
		<transform from="´o" to="ó"/>
		<transform from="´O" to="Ó"/>
		<transform from="´u" to="ú"/>
		<transform from="´U" to="Ú"/>
		<transform from="´y" to="ý"/>
		<transform from="´Y" to="Ý"/>
	</transforms>
</keyboard>

=== aradzie/keybr.com/packages/keybr-keyboard-generator/cldr-keyboards-43.0/keyboards/android/vi-t-k0-android-600dpi.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE keyboard SYSTEM "../dtd/ldmlKeyboard.dtd">
<keyboard locale="vi-t-k0-android-600dpi">
	<version platform="4.4" number="$Revision$"/>
	<names>
		<name value="Vietnamese (600dpi)"/>
	</names>
	<keyMap>
		<map iso="D01" to="q"/>
		<map iso="D02" to="w"/>
		<map iso="D03" to="e" longPress="è é ẻ ẽ ẹ ê ề ế ể ễ ệ"/>
		<map iso="D04" to="r"/>
		<map iso="D05" to="t"/>
		<map iso="D06" to="y" longPress="ỳ ý ỷ ỹ ỵ"/>
		<map iso="D07" to="u" longPress="ù ú ủ ũ ụ ư ừ ứ ử ữ ự"/>
		<map iso="D08" to="i" longPress="ì í ỉ ĩ ị"/>
		<map iso="D09" to="o" longPress="ò ó ỏ õ ọ ô ồ ố ổ ỗ ộ ơ ờ ớ ở ỡ ợ"/>
		<map iso="D10" to="p"/>
		<map iso="C01" to="a" longPress="à á ả ã ạ ă ằ ắ ẳ ẵ ặ â ầ ấ ẩ ẫ ậ"/>
		<map iso="C02" to="s"/>
		<map iso="C03" to="d" longPress="đ"/>
		<map iso="C04" to="f"/>
		<map iso="C05" to="g"/>
		<map iso="C06" to="h"/>
		<map iso="C07" to="j"/>
		<map iso="C08" to="k"/>
		<map iso="C09" to="l"/>
		<map iso="B01" to="z"/>
		<map iso="B02" to="x"/>
		<map iso="B03" to="c"/>
		<map iso="B04" to="v"/>
		<map iso="B05" to="b"/>
		<map iso="B06" to="n"/>
		<map iso="B07" to="m"/>
		<map iso="B08" to="!"/> <!-- , -->
		<map iso="B09" to="?"/> <!-- . -->
		<map iso="A01" to="/"/> <!-- (2 keys to left of space) -->
		<map iso="A02" to=" "/> <!-- (key to left of space) -->
		<map iso="A03" to=","/> <!-- space -->
		<map iso="A04" to="." longPress="…"/> <!-- (key to right of space) -->
	</keyMap>
	<keyMap modifiers="shift caps">
		<map iso="D01" to="Q"/>
		<map iso="D02" to="W"/>
		<map iso="D03" to="E" longPress="È É Ẻ Ẽ Ẹ Ê Ề Ế Ể Ễ Ệ"/>
		<map iso="D04" to="R"/>
		<map iso="D05" to="T"/>
		<map iso="D06" to="Y" longPress="Ỳ Ý Ỷ Ỹ Ỵ"/>
		<map iso="D07" to="U" longPress="Ù Ú Ủ Ũ Ụ Ư Ừ Ứ Ử Ữ Ự"/>
		<map iso="D08" to="I" longPress="Ì Í Ỉ Ĩ Ị"/>
		<map iso="D09" to="O" longPress="Ò Ó Ỏ Õ Ọ Ô Ồ Ố Ổ Ỗ Ộ Ơ Ờ Ớ Ở Ỡ Ợ"/>
		<map iso="D10" to="P"/>
		<map iso="C01" to="A" longPress="À Á Ả Ã Ạ Ă Ằ Ắ Ẳ Ẵ Ặ Â Ầ Ấ Ẩ Ẫ Ậ"/>
		<map iso="C02" to="S"/>
		<map iso="C03" to="D" longPress="Đ"/>
		<map iso="C04" to="F"/>
		<map iso="C05" to="G"/>
		<map iso="C06" to="H"/>
		<map iso="C07" to="J"/>
		<map iso="C08" to="K"/>
		<map iso="C09" to="L"/>
		<map iso="B01" to="Z"/>
		<map iso="B02" to="X"/>
		<map iso="B03" to="C"/>
		<map iso="B04" to="V"/>
		<map iso="B05" to="B"/>
		<map iso="B06" to="N"/>
		<map iso="B07" to="M"/>
		<map iso="B08" to="!"/> <!-- , -->
		<map iso="B09" to="?"/> <!-- . -->
		<map iso="A01" to="/"/> <!-- (2 keys to left of space) -->
		<map iso="A02" to=" "/> <!-- (key to left of space) -->
		<map iso="A03" to=","/> <!-- space -->
		<map iso="A04" to="." longPress="…"/> <!-- (key to right of space) -->
	</keyMap>
	<keyMap modifiers="opt">
		<map iso="D01" to="1" longPress="¹ ½ ⅓ ¼ ⅛"/> <!-- Q -->
		<map iso="D02" to="2" longPress="² ⅔"/> <!-- W -->
		<map iso="D03" to="3" longPress="³ ¾ ⅜"/> <!-- E -->
		<map iso="D04" to="4" longPress="⁴"/> <!-- R -->
		<map iso="D05" to="5" longPress="⅝"/> <!-- T -->
		<map iso="D06" to="6"/> <!-- Y -->
		<map iso="D07" to="7" longPress="⅞"/> <!-- U -->
		<map iso="D08" to="8"/> <!-- I -->
		<map iso="D09" to="9"/> <!-- O -->
		<map iso="D10" to="0" longPress="ⁿ ∅"/> <!-- P -->
		<map iso="C01" to="@"/> <!-- A -->
		<map iso="C02" to="#"/> <!-- S -->
		<map iso="C03" to="₫" longPress="$ ¢ € £ ¥ ₱"/> <!-- D -->
		<map iso="C04" to="%" longPress="‰"/> <!-- F -->
		<map iso="C05" to="&amp;"/> <!-- G -->
		<map iso="C06" to="-" longPress="_ – — ·"/> <!-- H -->
		<map iso="C07" to="+" longPress="±"/> <!-- J -->
		<map iso="C08" to="(" longPress="&lt; { ["/> <!-- K -->
		<map iso="C09" to=")" longPress="&gt; } ]"/> <!-- L -->
		<map iso="B01" to="\"/> <!-- Z -->
		<map iso="B02" to="="/> <!-- X -->
		<map iso="B03" to="*" longPress="† ‡ ★"/> <!-- C -->
		<map iso="B04" to="\u{22}" longPress="“ ” « »"/> <!-- V  to= "  -->
		<map iso="B05" to="&apos;" longPress="‘ ’ ‹ ›"/> <!-- B -->
		<map iso="B06" to=":"/> <!-- N -->
		<map iso="B07" to=";"/> <!-- M -->
		<map iso="B08" to="!" longPress="¡"/> <!-- , -->
		<map iso="B09" to="?" longPress="¿"/> <!-- . -->
		<map iso="A00" to="_"/> <!-- (3 keys to left of space) -->
		<map iso="A01" to="/"/> <!-- (2 keys to left of space) -->
		<map iso="A02" to=" "/> <!-- (key to left of space) -->
		<map iso="A03" to=","/> <!-- space -->
		<map iso="A04" to="." longPress="…"/> <!-- (key to right of space) -->
	</keyMap>
	<keyMap modifiers="opt+shift">
		<map iso="D01" to="~"/> <!-- Q -->
		<map iso="D02" to="`"/> <!-- W -->
		<map iso="D03" to="|"/> <!-- E -->
		<map iso="D04" to="•" longPress="♪ ♥ ♠ ♦ ♣"/> <!-- R -->
		<map iso="D05" to="√"/> <!-- T -->
		<map iso="D06" to="Π" longPress="π"/> <!-- Y -->
		<map iso="D07" to="÷"/> <!-- U -->
		<map iso="D08" to="×"/> <!-- I -->
		<map iso="D09" to="¶" longPress="§"/> <!-- O -->
		<map iso="D10" to="∆"/> <!-- P -->
		<map iso="C01" to="£"/> <!-- A -->
		<map iso="C02" to="€"/> <!-- S -->
		<map iso="C03" to="$" longPress="¢"/> <!-- D -->
		<map iso="C04" to="¢"/> <!-- F -->
		<map iso="C05" to="^" longPress="↑ ↓ ← →"/> <!-- G -->
		<map iso="C06" to="°" longPress="′ ″"/> <!-- H -->
		<map iso="C07" to="=" longPress="≠ ≈ ∞"/> <!-- J -->
		<map iso="C08" to="{"/> <!-- K -->
		<map iso="C09" to="}"/> <!-- L -->
		<map iso="B01" to="\"/> <!-- Z -->
		<map iso="B02" to="©"/> <!-- X -->
		<map iso="B03" to="®"/> <!-- C -->
		<map iso="B04" to="™"/> <!-- V -->
		<map iso="B05" to="℅"/> <!-- B -->
		<map iso="B06" to="["/> <!-- N -->
		<map iso="B07" to="]"/> <!-- M -->
		<map iso="B08" to="¡"/> <!-- ,  base=! -->
		<map iso="B09" to="¿"/> <!-- .  base=? -->
		<map iso="A00" to="&lt;" longPress="‹ ≤ «"/> <!-- (3 keys to left of space) -->
		<map iso="A01" to="&gt;" longPress="› ≥ »"/> <!-- (2 keys to left of space)  base=/ -->
		<map iso="A02" to=" "/> <!-- (key to left of space) -->
		<map iso="A03" to=","/> <!-- space -->
		<map iso="A04" to="." longPress="…"/> <!-- (key to right of space) -->
	</keyMap>
</keyboard>

=== aradzie/keybr.com/packages/keybr-generators/cldr-keyboards-43.0/keyboards/android/th-t-k0-android-768dpi.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE keyboard SYSTEM "../dtd/ldmlKeyboard.dtd">
<keyboard locale="th-t-k0-android-768dpi">
	<version platform="4.4" number="$Revision$"/>
	<names>
		<name value="Thai (768dpi)"/>
	</names>
	<keyMap>
		<map iso="E01" to="ๅ"/> <!-- 1 -->
		<map iso="E02" to="/" longPress="๑"/> <!-- 2 -->
		<map iso="E03" to="_" longPress="๒"/> <!-- 3 -->
		<map iso="E04" to="ภ" longPress="๓"/> <!-- 4 -->
		<map iso="E05" to="ถ" longPress="๔"/> <!-- 5 -->
		<map iso="E06" to="\u{E38}"/> <!-- 6  to=  ุ  -->
		<map iso="E07" to="\u{E36}"/> <!-- 7  to=  ึ  -->
		<map iso="E08" to="ค" longPress="๕"/> <!-- 8 -->
		<map iso="E09" to="ต" longPress="๖"/> <!-- 9 -->
		<map iso="E10" to="จ" longPress="๗"/> <!-- 0 -->
		<map iso="E11" to="ข" longPress="๘"/> <!-- - -->
		<map iso="E12" to="ช" longPress="๙"/> <!-- = -->
		<map iso="D01" to="ๆ" longPress="๐"/> <!-- Q -->
		<map iso="D02" to="ไ"/> <!-- W -->
		<map iso="D03" to="ำ"/> <!-- E -->
		<map iso="D04" to="พ"/> <!-- R -->
		<map iso="D05" to="ะ"/> <!-- T -->
		<map iso="D06" to="\u{E31}"/> <!-- Y  to=  ั  -->
		<map iso="D07" to="\u{E35}"/> <!-- U  to=  ี  -->
		<map iso="D08" to="ร"/> <!-- I -->
		<map iso="D09" to="น"/> <!-- O -->
		<map iso="D10" to="ย"/> <!-- P -->
		<map iso="D11" to="บ"/> <!-- [ -->
		<map iso="D12" to="ล"/> <!-- ] -->
		<map iso="C01" to="ฟ"/> <!-- A -->
		<map iso="C02" to="ห"/> <!-- S -->
		<map iso="C03" to="ก"/> <!-- D -->
		<map iso="C04" to="ด"/> <!-- F -->
		<map iso="C05" to="เ"/> <!-- G -->
		<map iso="C06" to="\u{E49}"/> <!-- H  to=  ้  -->
		<map iso="C07" to="\u{E48}"/> <!-- J  to=  ่  -->
		<map iso="C08" to="า"/> <!-- K -->
		<map iso="C09" to="ส"/> <!-- L -->
		<map iso="C10" to="ว"/> <!-- ; -->
		<map iso="C11" to="ง"/> <!-- ' -->
		<map iso="C12" to="ฃ"/> <!-- (key to right of ') -->
		<map iso="B01" to="ผ"/> <!-- Z -->
		<map iso="B02" to="ป"/> <!-- X -->
		<map iso="B03" to="แ"/> <!-- C -->
		<map iso="B04" to="อ"/> <!-- V -->
		<map iso="B05" to="\u{E34}"/> <!-- B  to=  ิ  -->
		<map iso="B06" to="\u{E37}"/> <!-- N  to=  ื  -->
		<map iso="B07" to="ท"/> <!-- M -->
		<map iso="B08" to="ม"/> <!-- , -->
		<map iso="B09" to="ใ"/> <!-- . -->
		<map iso="B10" to="ฝ"/> <!-- / -->
		<map iso="A02" to=","/> <!-- (key to left of space) -->
		<map iso="A03" to=" "/> <!-- space -->
		<map iso="A04" to="." longPress="# ! , ? - : ' @"/> <!-- (key to right of space) -->
	</keyMap>
	<keyMap modifiers="opt">
		<map iso="D01" to="1" longPress="¹ ½ ⅓ ¼ ⅛"/> <!-- Q  base=ๆ -->
		<map iso="D02" to="2" longPress="² ⅔"/> <!-- W  base=ไ -->
		<map iso="D03" to="3" longPress="³ ¾ ⅜"/> <!-- E  base=ำ -->
		<map iso="D04" to="4" longPress="⁴"/> <!-- R  base=พ -->
		<map iso="D05" to="5" longPress="⅝"/> <!-- T  base=ะ -->
		<map iso="D06" to="6"/> <!-- Y  base= ั -->
		<map iso="D07" to="7" longPress="⅞"/> <!-- U  base= ี -->
		<map iso="D08" to="8"/> <!-- I  base=ร -->
		<map iso="D09" to="9"/> <!-- O  base=น -->
		<map iso="D10" to="0" longPress="ⁿ ∅"/> <!-- P  base=ย -->
		<map iso="C01" to="@"/> <!-- A  base=ฟ -->
		<map iso="C02" to="#"/> <!-- S  base=ห -->
		<map iso="C03" to="฿" longPress="$ ¢ € £ ¥ ₱"/> <!-- D  base=ก -->
		<map iso="C04" to="%" longPress="‰"/> <!-- F  base=ด -->
		<map iso="C05" to="&amp;"/> <!-- G  base=เ -->
		<map iso="C06" to="-" longPress="_ – — ·"/> <!-- H  base= ้ -->
		<map iso="C07" to="+" longPress="±"/> <!-- J  base= ่ -->
		<map iso="C08" to="(" longPress="&lt; { ["/> <!-- K  base=า -->
		<map iso="C09" to=")" longPress="&gt; } ]"/> <!-- L  base=ส -->
		<map iso="B01" to="*" longPress="† ‡ ★"/> <!-- Z  base=ผ -->
		<map iso="B02" to="\u{22}" longPress="“ ” « »"/> <!-- X  base=ป  to= "  -->
		<map iso="B03" to="&apos;" longPress="‘ ’ ‹ ›"/> <!-- C  base=แ -->
		<map iso="B04" to=":"/> <!-- V  base=อ -->
		<map iso="B05" to=";"/> <!-- B  base= ิ -->
		<map iso="B06" to="!" longPress="¡"/> <!-- N  base= ื -->
		<map iso="B07" to="?" longPress="¿"/> <!-- M  base=ท -->
		<map iso="A00" to="_"/> <!-- (3 keys to left of space) -->
		<map iso="A01" to="/"/> <!-- (2 keys to left of space) -->
		<map iso="A02" to=" "/> <!-- (key to left of space)  base=, -->
		<map iso="A03" to=","/> <!-- space -->
		<map iso="A04" to="."/> <!-- (key to right of space) -->
	</keyMap>
	<keyMap modifiers="opt+shift">
		<map iso="D01" to="~"/> <!-- Q  base=ๆ -->
		<map iso="D02" to="`"/> <!-- W  base=ไ -->
		<map iso="D03" to="|"/> <!-- E  base=ำ -->
		<map iso="D04" to="•" longPress="♪ ♥ ♠ ♦ ♣"/> <!-- R  base=พ -->
		<map iso="D05" to="√"/> <!-- T  base=ะ -->
		<map iso="D06" to="Π" longPress="π"/> <!-- Y  base= ั -->
		<map iso="D07" to="÷"/> <!-- U  base= ี -->
		<map iso="D08" to="×"/> <!-- I  base=ร -->
		<map iso="D09" to="¶" longPress="§"/> <!-- O  base=น -->
		<map iso="D10" to="∆"/> <!-- P  base=ย -->
		<map iso="C01" to="£"/> <!-- A  base=ฟ -->
		<map iso="C02" to="€"/> <!-- S  base=ห -->
		<map iso="C03" to="$" longPress="¢"/> <!-- D  base=ก -->
		<map iso="C04" to="¢"/> <!-- F  base=ด -->
		<map iso="C05" to="^" longPress="↑ ↓ ← →"/> <!-- G  base=เ -->
		<map iso="C06" to="°" longPress="′ ″"/> <!-- H  base= ้ -->
		<map iso="C07" to="=" longPress="≠ ≈ ∞"/> <!-- J  base= ่ -->
		<map iso="C08" to="{"/> <!-- K  base=า -->
		<map iso="C09" to="}"/> <!-- L  base=ส -->
		<map iso="B01" to="\"/> <!-- Z  base=ผ -->
		<map iso="B02" to="©"/> <!-- X  base=ป -->
		<map iso="B03" to="®"/> <!-- C  base=แ -->
		<map iso="B04" to="™"/> <!-- V  base=อ -->
		<map iso="B05" to="℅"/> <!-- B  base= ิ -->
		<map iso="B06" to="["/> <!-- N  base= ื -->
		<map iso="B07" to="]"/> <!-- M  base=ท -->
		<map iso="A00" to="&lt;" longPress="‹ ≤ «"/> <!-- (3 keys to left of space) -->
		<map iso="A01" to="&gt;" longPress="› ≥ »"/> <!-- (2 keys to left of space) -->
		<map iso="A02" to=" "/> <!-- (key to left of space)  base=, -->
		<map iso="A03" to=","/> <!-- space -->
		<map iso="A04" to="."/> <!-- (key to right of space) -->
	</keyMap>
</keyboard>
